### ISSUE TITLE
VSL API: "duplicate link" errors in request grouping when vsl_buffer is increased

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1830]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1830

**Comment by nigoroll** [comment]
@mbgrydeland @slimhazard do IUC that this really is still open and not yet addressed? Should I have a look?

**Comment by slimhazard** [comment]
Yes, we're getting the error up to about 750 times/second at peak load, on the order of 25 to 30 million times a day.

**Comment by slimhazard** [comment]
Is there anything that can be done to try to discover the problem here? (@mbgrydeland ?)

Our VSL tool has, as of this moment, accumulated over 130 million VSL errors during its uptime (which appears to be about 6 days right now). Presumably, most or all of these are the "duplicate link" errors, at least we hope so.

As described in the trac ticket, we cannot determine any genuine defects in the data obtained from VSL as a result of this error, which is why it doesn't count as a showstopper. However, we are forced to routinely ignore VSL error messages, coming in at millions per day, and may very well be missing problems that are genuine and serious.

Since the problem was first reported in December 2015, we really should think of a way to move forward.

**Comment by hermunn** [comment]
Backport review: Backported as fd958451b8.
