### ISSUE TITLE
Varnish exits with bad vcl.load configname

### ISSUE THREAD

**Issue by rezan** [varnishcache/varnish-cache#1963]
If you provide a configname with a `/` to `vcl.load`, varnishadm and varnishd will exit.

## Expected Behavior
An error.

## Current Behavior
varnishd exit (no panic).

varnishadm:
```
> bin/varnishadm vcl.load /test/name blah
CLI communication error (hdr)
Command failed with error code 400
```

varnishd:
```
> varnishd -d -a ":8888" -f "test.vcl"
Debug: Platform: Linux,3.13.0-85-generic,x86_64,-jnone,-smalloc,-smalloc,-hcritbit

200 283     
-----------------------------
Varnish Cache CLI 1.0
-----------------------------
Linux,3.13.0-85-generic,x86_64,-jnone,-smalloc,-smalloc,-hcritbit
varnish-trunk revision 7e90a2b

Type 'help' for command list.
Type 'quit' to close CLI session.
Type 'start' to launch worker process.

start
Debug: Child (4474) Started
200 0       

Info: Child (4474) said Child starts
Error: Cannot create VCL directory 'vcl_/test/name': No such file or directory

>
```

## Possible Solution
Haven't digged in yet, but this should just be an error with no exit.

## Steps to Reproduce (for bugs)
1. Start varnish
2. bin/varnishadm vcl.load /test/name blah

## Context
Mistakenly swapped the configname and vcl path in vcl.load. Resulted in varnishd exiting. This happens on 4.1 and master. Also happens when varnishd is running as a service or via `-d`.

## Your Environment
* Version used: varnishd (varnish-trunk revision 7e90a2b)
* Operating System and version: Ubuntu 14

**Comment by maozza** [comment]
got the same problem with version 4.1:

varnish-4.1.2-1.el7 on CentOS Linux release 7.2.1511
when mistakenly run
vcl.load <filename> <configname> 
instead of : 
vcl.load <configname> <filename>

the server crash.
example: 
`
[root@Varnish ~]# varnishadm 
200        
-----------------------------
Varnish Cache CLI 1.0
-----------------------------
Linux,3.10.0-327.10.1.el7.x86_64,x86_64,-junix,-smalloc,-sfile,-smalloc,-hcritbit
varnish-4.1.2 revision 0d7404e

Type 'help' for command list.
Type 'quit' to close CLI session.


varnish> 
varnish> 
varnish> vcl.load /etc/varnish/test.file name
[root@Varnish ~]# varnishadm 
Connection failed (127.0.0.1 6082): (null)
[root@Varnish ~]# systemctl restart varnish
[root@Varnish ~]# varnishadm 
200        
-----------------------------
Varnish Cache CLI 1.0
-----------------------------
Linux,3.10.0-327.10.1.el7.x86_64,x86_64,-junix,-smalloc,-sfile,-smalloc,-hcritbit
varnish-4.1.2 revision 0d7404e

`

**Comment by lkarsten** [comment]
Test case:
```
diff --git a/bin/varnishtest/tests/b00032.vtc b/bin/varnishtest/tests/b00032.vtc
index a36634f..27175e8 100644
--- a/bin/varnishtest/tests/b00032.vtc
+++ b/bin/varnishtest/tests/b00032.vtc
@@ -26,3 +26,4 @@ varnish v1 -clierr 106 {vcl.load vcl3 ./nonexistent.vcl}
 
 varnish v1 -cliok "vcl.discard vcl2"
 
+varnish v1 -clierr 106 {vcl.load /wrong/argument/order/default.vcl vcl4}

```

**Comment by hermunn** [comment]
Backport review: Backported as 3cc70e758f08b3c7a9a922cd2f86c91a6bfbfb80.
