### ISSUE TITLE
[5.0.0] Quick vcl.load, vcl.use and vcl.discard leads to 50x/Director returned no backends

### ISSUE THREAD

**Issue by zstyblik** [varnishcache/varnish-cache#2195]
Hello,

it's possible we're doing something wrong, although we haven't seen such rate of 50x with Varnish 4.0.

What is being done is:
* varnish is started with `default.vcl`
* new VCLs, resp. directors and backends are then periodically loaded and old ones discarded through the lifetime of varnish instance

The usual view in varnishadm is:
```
discarded   auto/busy         20 vcl_b09ccef2-0bce-4ced-9901-282a488c2d39
discarded   auto/busy         87 vcl_b223fe02-4946-4008-b135-fc6fff8228dc
discarded   auto/busy         27 vcl_32c20ded-7dce-4111-8e83-a471dfde45f8
discarded   auto/busy         76 vcl_8eedfc71-f337-4265-848c-23fcfa66771e
active      auto/warm         63 vcl_97ee0121-4505-4b3f-8d90-91e136aaec9e
```

However, we've noticed that there are way too many 50x when VCL is loaded and used right away like so:

```
varnishadm vlc.load <vcl>
varnishadm vlc.use <vlc>
```

My understand is this is due to the fact that backend starts as sick and at least two health probes must succeed before it's marked healthy(please, confirm). What I don't understand is we didn't see this behaviour with Varnish 4.0.

We've managed to improve situation a bit by adding (thumb sucked) `% sleep 5;` between `vcl.load` and `vcl.use` which results in:

```
discarded   auto/busy         30 vcl_91de4c43-5577-4b50-a7da-89b2e75264a5
active      auto/warm        510 vcl_76ac2705-108b-4e66-b831-a5c90adbd181
available   auto/warm          0 vcl_4e3800e2-c4cc-4b06-91cf-8fb9ef9f041f
```

I assume this gives Varnish to send health probes and mark those Directors/BEs as healthy(again, please, confirm).

Additional change we've done, we were forced to do, is to replace `return (fetch);` to `return (miss);` in `sub vcl_hit {}`.

## Steps to Reproduce (for bugs)
```
varnishadm vlc.load <vcl>
varnishadm vlc.use <vlc>
# Discard any VCLs which are available, although I don't think this is relevant for the issue
varnishadm vcl.discard <list of vcls with state 'available'>
```

## Context
Change VCL without reloading varnish. It most likely leads to degraded user experience.

## Your Environment
* Version used: 5.0.0
* Operating System and version: Debian 8 Jessie

**Comment by Dridi** [comment]
Consider setting the initial state of your probe. This is not related to VCL switching but most likely to the shape of your HTTP traffic.

See `man vcl(7)` for details but if you need two probe tries to succeed to get a healthy backend, then consider adding this to your probe to *start* with a healthy backend:

```vcl
probe your_probe {
    [...]
    .initial = 2;
}
```

**Comment by zstyblik** [comment]
Hello,

sorry for not providing more info as I didn't know what is and isn't relevant. Please, feel free to ask for more. We have `default.vcl` and then `backends.vcl`. `backends.vcl` is the file which receives updates.

In `default.vcl` we have:

```
# /health probe.
probe health {
    .url       = "/health";
    .interval  = 1s;
    .timeout   = 1s;
    .window    = 5;
    .threshold = 3;
    .initial   = 2;
}
```

In `backends.vcl` we have something like:

```
backend mybackend_1234 {
  .host = "192.168.1.1";
  .port = "1234";
  .probe = health;
}

sub vcl_init {
    new directory_mybackend = directors.round_robin();
    directory_mybackend.add_backend(mybackend_1234);
}
```

I'm sorry if I've messed up something due to edits. Also, any replies are appreciated.

**Comment by Dridi** [comment]
If you want to start with healthy backends, `initial` needs to be at least equal to `threshold`.

In your case:

```
probe health {
    .url       = "/health";
    .interval  = 1s;
    .timeout   = 1s;
    .window    = 5;
    .threshold = 3;
    .initial   = 3;
}
```

**Comment by zstyblik** [comment]
Hello @Dridi,

I agree this would have marked backends as healthy and probably would have avoided 50x, but I don't think anybody wants to route client traffic into unknown. In other words, this just shifts the problem elsewhere. I'm quite fine if the described assumptions were confirmed and described behaviour would be documented, resp. that VCL should be kept as `available/warm` for period of time _t_ and then and only then made active. Would such solution work for you guys?
Dynamic VCL reload without the need of varnish restart is awesome feature despite the fact it probably has some short-comings.

Thank you.

**Comment by Dridi** [comment]
That's a packaging concern: basically we ship different reload scripts for Debian-based and Red Hat-based systems. I certainly don't disagree with a warm-up period when doing a reload, defaulting to zero (current behavior).

Can you please open a new ticket in the `pkg-varnish-cache` repository to discuss that? I'm closing this ticket because there's no actual bug in Varnish itself. Somewhat unrelated, I'd like to see reload scripts converge instead of maintaining two different instances, but that's also not something we want to discuss here. If we add this delay today, we may do it in two places...

**Comment by zstyblik** [comment]
I can do that, however I don't believe there is one delay to rule them all as this will depend on configuration of health probe. Of course, such assumption can be wrong. That's why I've suggested to document this behaviour. Also, I will repeat this behaviour wasn't in Varnish 4.0, at least not at this scale.

**Comment by Dridi** [comment]
This is indeed something that appeared in Varnish 4.1 because of dynamic backends. Long story short, VCLs used to share backends, now they own them. Which means that during a reload, you get a whole set of new backends (but they can share their TCP pools) and consequently fresh probes starting from scratch.

Please note that VCLs in 4.0 would share backends having the same:

- name
- ipv4 address
- ipv6 address
- port

We've had discussions about global backends that would be shared by VCLs but it has yet to make it in the roadmap. I realize this is something that should be better documented, I'm reopening this issue and will close it with a docfix. For the reload delay, please file a packaging issue in `pkg-varnish-cache`.

Thanks!

**Comment by Dridi** [comment]
Regarding the reload delay, there's an ongoing review in varnishcache/pkg-varnish-cache#70.

**Comment by gquintard** [comment]
varnishcache/pkg-varnish-cache#70 has been merged, closing.
