### ISSUE TITLE
Coverity not being run

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2213]
Did we loose the automatic coverity runs with Jenkins ?

Does anybody know how this actually works in the first place ?

**Comment by daghf** [comment]
My bad.

I updated the coverity tool after they started complaining our version was too old. The `cov-int ` metadata directory built by the previous version apparently is not compatible with the new version, so that made our weekly update job fail.

I wiped the old dir and thing should be back to normal now.

A new upload is currently processing in Coverity, should be ready any minute.

**Comment by hermunn** [comment]
Backport review: We do not have coverity running for 4.1, as it is in maintenance mode, but maybe we should? I passe the question to @daghf.
