### ISSUE TITLE
Cannot convert BODY to STRING

### ISSUE THREAD

**Issue by joshuaspence** [varnishcache/varnish-cache#2229]
I am trying to set the response to the contents of a file, after performing a regex substition. Basically, I am trying to do this:

```
sub vcl_backend_error {
  set beresp.body = std.fileread("/etc/varnish/error.html");
  set beresp.body = regsuball(beresp.body, "{{ beresp\.status }}", beresp.status);
  return (deliver);
}
```

This doesn't seem to work, however, and instead I get the following error. Is this expected?

```
Cannot convert BODY to STRING.
```

**Comment by bsdphk** [comment]
Yes, the body variables are write-only by design, because the data may have been passed through a filter (gzip) and no longer be available in the original form.

The right solution to what you are trying to do is probably a VMOD which takes a list of variables to replace and feeds the file to the body without the detour through the workspace.

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.
