### ISSUE TITLE
Continuation of wrong default response format on error 503

### ISSUE THREAD

**Issue by 1Hyena** [varnishcache/varnish-cache#2309]
https://github.com/varnishcache/varnish-cache/issues/2308

@Dridi
I was almost satisfied with the response from @gquintard but since you insist this is not a bug I insist this is indeed a bug now that you have so blatantly jumped into defense mode. Typical for ingrown software projects. And others are always wrong because of their lack of understanding, if only they understood things the same level you do then they would agree with you, it's just they are inferior and thus incompatible for any discussion, right? ;)

**Comment by gquintard** [comment]
Please excuse @dridi, he's French :-)

The point of the discussion is: what you want isn't exactly possible (no config file), but the vcl needed to do your bidding is only a few lines long. But I 'd rather discuss it on IRC or on the mailing list than on Gh.

**Comment by 1Hyena** [comment]
@gquintard 
Thanks again. Github should really implement some chat or less formal means of discussion. Nowadays every dev knows how to use github and has an account there anyway. Getting into a particular project's custom discussion board is sort of an inconvenient investment if there is no promise of a cake in the end.
Anyway, good luck with everything! I have good feelings towards varnish and especially I like the fact that it has support for epoll.

**Comment by Dridi** [comment]
I'm certainly no longer in the mood of discussing your questions if you ever move this thread to the varnish-misc mailing list as kindly asked previously. I was not in defense mode, but rather in my usual trainer mindset [1] but now I will mind my own business because I'm no longer interested in helping yours thank you very much.

[1] yes, because on top of being inexcusably French I also enjoy training people on Varnish
