### ISSUE TITLE
6.0 Toplevel Planning

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2318]
This ticket is for discussing what we might want to wreck, it is not in any way a commitment to undertake any or all of these ideas.

**Transport related VCL changes**

```
sub vcl_http1 {}  // Only place you do return(pipe) from in the new world
sub vcl_http2 {} // For tweaking SETTINGS etc.
sub vcl_proxy {} // Probably only for ACL'ing
```

**Non-IP sockets**

(UNIX-local, QUIC etc.)

This I think is mainly a question of VCL syntax issues.

**VCL/VMOD object model**

The big one...

**Other VCL extensions**

`sub probe_response{}`

Body producing sub's (for sticking bits into VDP/VFP pipes for gzip, esi etc.)  Probably something like:

```
sub vcl_synthetic {
    set resp.bodyfunc = foobar;
}

sub foobar {
    set body.bytes = "<HTML>sdfksfsfsfsd";
    set body.bytes = req.http.bla + "//" + req.protocol ...
}
```

Where the bodyfunc gets called after the "real" vcl function has run.

Keeping VCL in sync, at least syntax wise with for instance Fastly is important.

**Loadable extensions**

Like vmods, but not bound to a single VCL

Could allow "global backends", new protocols etc.

**Comment by nigoroll** [comment]
things on my list
* `beresp.filter_list` see https://lists.gt.net/varnish/dev/42050#42050
* add status and reason to `abandon`, add `return(error(s, m))` to fail into `vcl_backend_error` https://lists.gt.net/varnish/dev/41542#41542
* reading/parsind bodies (iterators? STRING_LIST? BLOB_LIST?)
* re-do STRING_LIST without varargs
* re-work tunables to not tune the overall size, but rather the headroom reamaining for use in vcl https://lists.gt.net/varnish/dev/39240#39240
* native vcl variables (scope local (per vcl sub)/task/vcl/global)
  * native list type
  * variables to reference objects
* objects as vmod function arguments
* generalize VTIM interface, compile-time choice of implementation (uint64 instead of double)
* Workspace open/close semantics, append https://github.com/nigoroll/libvmod-geoip2/blob/lookup_fields/src/ws_ext.c
* backend refcounting and GC

**Comment by Dridi** [comment]
Off the top of my head:

- IP-less ACLs (aka named listen addresses, I'm supposed to draft a spec, relates to VIP 17 too)
- libvarnishapi 2.0 (as #2314 suggests, and maybe expose more useful symbols)
- the `varnishreload` script from varnishcache/pkg-varnish-cache#70
- `sub vcl_protocol_switch` to allow/reject a piped transaction on 101 responses
- storage bypass for huge objects (`return(pipe)` or some pipe-like stevedore)

I will update that list before Monday if I remember other things later.

**Comment by slimhazard** [comment]
Repeating a few things from VIP17, since the question is about "what do we want to wreck" -- since we are considering non-IP sockets, the ``*.ip`` variable names in VCL become misnomers. The same goes for the VRT data type ``VCL_IP``, which is part of the public API for VMODs and vapi clients. "ip" also appears in a few VRT function names.

The ``.host`` field in backend definitions also becomes a misnomer if it can contain a UDS path, which is not a host.

The suggestion in VIP17 is to introduce ``addr`` for all of these names. So we'd have ``*.addr`` in VCL, ``VCL_ADDR`` in VRT, and an ``.addr`` field in backend definitions.

The suggestion is also to make this less of an immediate wreck by deprecating the old names, allowing them in the 6.0 release, and removing them from a future release.

There's less wreckage in the fact that ``VTCP``, ``vtcp.c`` etc become misnomers. But we could just live with that, or change it all at once in a single git commit.

**Comment by slimhazard** [comment]
Change the VMOD development model so that VCC files can be retired, and an RST file becomes the sole source of information about a VMOD.

Rather than converting VCC to RST (and then having issues like having to maintain documentation in two places on web-hosted repositories like github or gitlab, which expect a README in the repo root), the RST file should be able to serve for documentation without changes, and RST/python directives would be used for the VMOD declarations currently written in VCC.

This topic has come up in conversations on IRC, and @Dridi and I have expressed interest in getting something going, but it hasn't gotten far past the stage of "we ought to do that".

For VMOD authors, this change would be "wreckage-complete" (that is, as comprehensively wreckaging as anything could be) if VCCs immediately become obsolete in 6.0. So if we do it, we should do it so that VCCs files are deprecated but still work for at least another release, maybe for the next two releases (i.e for another year).

**Comment by bsdphk** [comment]
I have tried to synthesize the above here:  https://etherpad.net/p/V6.0

Feel free to join in...

**Comment by slimhazard** [comment]
A subject about Unix domain sockets that did not come up in the bugwash on May 1st was the suggestion in WIP17 that Varnish obtains credentials of the peer process -- uid & gid -- over the connected socket, and makes these available in VCL (for example via VMOD std).

Don't want to repeat everything here, the WIP discusses the idea in detail.

@Dridi opposed the idea in his mail to -dev on April 25th.

Unfortunately I again won't be able to make it to bugwash today (May 8th). But I want to put this out there again so that the subject isn't passed over in planning.

**Comment by slimhazard** [comment]
Apologies to @Dridi, on re-reading the mail I see that he didn't oppose the idea after all.

If there's not a controversy about this then maybe it doesn't need to be on the agenda for the planning bugwashes.

**Comment by nigoroll** [comment]
rework timeouts ? see 97d2c575521fc75a7e63c05545658131b300aece

**Comment by Dridi** [comment]
I'm still not done rewriting the unix domain sockets VIP 17, sorry about that.

I'd like to suggest another change, since we are breaking `libvarnishapi`: let log consumers know when a record was truncated. This way out-of-tree VUTs can react to that instead of processing incomplete data.

Our own `varnishlog` could change its output like this:

```
*   << Request  >> 2         
-   Begin          req 1 rxreq
[...]
-   Debug          complete
~   Debug          truncated, please note the tilde instead of the
[...]
```

**Comment by slimhazard** [comment]
+1 to @Dridi's suggestion, but I would say that the ``VSL`` tag should be used for this purpose, this is the sort of thing it's there for.

From vsl(7):
       VSL - VSL API warnings and error message
              Warnings and error messages generated by the VSL API while read‐
              ing the shared memory log.

**Comment by Dridi** [comment]
VIP 17 is ready for the next planning session, there's an ongoing thread on the dev mailing list to share comments before the next session.

https://github.com/varnishcache/varnish-cache/wiki/VIP-17:-Enable-Unix-domain-sockets-for-listen-and-backend-addresses

**Comment by nigoroll** [comment]
In #2354 @Dridi suggested that we postpone breaking changes given the fact that we did not finish many of those we planned for and I think this makes sense. We'd probably also want to consider to rather call the next release 5.2

**Comment by Dridi** [comment]
I'm moving the last bit of discussion from https://github.com/varnishcache/varnish-cache/issues/2325#issuecomment-301457374 to this ticket:

---

Bugwash consensus:

- all names to match `[a-zA-Z][a-zA-Z0-9_-]*`
  - no "weak" symbols allowed
- ~header names to stay their own thing syntax-wise~
  (edit: technically, other symbols will have the same syntax as headers)
- all symbol names to be unique (making r01569.vtc history)
- names "externally imported" (outside of VCL) to be namespace'd
  - `storage.Transient`, `socket.a0`, `label.my_label` etc

---

To that I will add that if all symbols are to be unique, we can't expect `default` to be usable for both the default backend and the default probe.

**Comment by fgsch** [comment]
6.0 is out now.
