### ISSUE TITLE
Problem forward requests to cpanel server through haproxy

### ISSUE THREAD

**Issue by behinam** [varnishcache/varnish-cache#2327]
Hi, I deployed an loadbalanced infrustructure. I am using haproxy as the loadbalancer and cpanel as backend webservers. I created a test host on the cpanel, and I can see the site in browser when I configure the website in my /etc/host with the cpanel server ip address. But when I change the ip to the loadbalancer it forwards the requests to /usr/local/apache/htdocs/ and I get the default cpanel server page(defaultwebpage.cgi). What configurations should I use in haproxy to redirects requests correctly?
Any help is appreciated.

**Comment by Dridi** [comment]
Hi, as indicated in the issue template you get when you open an issue, general questions don't belong on github. Please hit the misc mailing list instead or join the varnish channel on our IRC server.

http://varnish.org/support/

**Comment by behinam** [comment]
Did you read my question?
My question is irrelevant with varnish!!!
please before you answer, read questions..............

**Comment by gquintard** [comment]
Sooo, why post here?

**Comment by behinam** [comment]
Hi,
sorry for this mistake.
where should i ask on github about Haproxy?
can you help me?

**Comment by Dridi** [comment]
> Did you read my question?
My question is irrelevant with varnish!!!
please before you answer, read issue and questions..............

As a matter of fact, no. I didn't read it carefully and saw "proxy" instead of "haproxy". Because in Varnish we support the proxy protocol from haproxy, I assumed you had a configuration problem in this area. My response was generic, I use it when invalid issues are opened (nothing against you in particular).

> where should i ask on github about Haproxy?
can you help me?

I'm afraid if you need help with haproxy we aren't the right folks. The project is not on github so you can try their mailing lists or other places like stackoverflow.

**Comment by gquintard** [comment]
http://www.haproxy.org/#tact
