### ISSUE TITLE
VCL table lookups

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2355]
This is an idea I had floating around for years and someone asked me exactly that during a recent training course:

> Is there a way to easily match a string against a list of strings in VCL?

The main use cases would be backend/director selection or VCL label switch based on a host name. This is especially useful when a backend or a label would be responsible for various host names, making it tedious using regular expressions, usually implemented with a series of if-elif branches. I may be wrong remembering the numbers but I recall a user with 800-ish domains, and I think 300-ish of them were managed by a single set of backends (behind a director).

When I point people to @gquintard's vmod-stendhal they push back and say they'd prefer a pure VCL solution.

I have a [patch](https://github.com/Dridi/varnish-cache/commit/e58a060e9d62b4ebfa290b1e59ec72af6194cc31) with the following test:

```vcl
varnishtest "table lookup"

server s1 { } -start

varnish v1 -vcl+backend {
        import debug;

        table empty { }

        table varnish-hosts {
                "varnish.org";
                "www.varnish.org";
                "varnish-cache.org";
                "www.varnish-cache.org";
        }

        sub vcl_recv {
                if (debug.table_lookup(empty, req.http.host)) {
                        return (fail);
                }
                if (req.http.host ~ varnish-hosts) {
                        return (synth(200));
                }
                if (req.http.host !~ varnish-hosts) {
                        return (synth(404));
                }
        }
} -start

client c1 {
        txreq
        rxresp
        expect resp.status == 404

        txreq -hdr "Host: www.varnish-cache.org"
        rxresp
        expect resp.status == 200
} -run
```

The lookup is done with a simple `bsearch(3)`, and the strings are static, not regular expressions. Also, as the table name may hint, it's written on top of the #2354 patch set that makes it slightly easier to implement (in addition to allowing `-` in a table name). I accidentally made it available to VMODs too.

I can submit it as soon as #2354 lands in master.

Since I'm getting familiar with libvcc again, I could also make a `VCL_REGEX` type for VMODs since last time we discussed it the answer was "send patches". #2354 doesn't cover all of #2325 anyway so I still have work to do in this area for 6.0 and I wouldn't mind (but no promises).

Thoughts?

**Comment by gquintard** [comment]
I like the vcl as a minimal language, so I would be against. As you pointed, a vmod can easily do this.

This ticket could be a sign that we need to improve the vmod story. Maybe with dockerfiles to automatically produce the packages from a github account?

**Comment by slimhazard** [comment]
I think the right answer to this request is to push back against the pushback. This is the sort of thing that cries out for solutions with VMODs.

There are other use cases that involve matching against lists of strings or patterns, and they're not quite the same. At least as common as matching against Host, in my experience, is matching against URLs to select a backend. And that's not usually a complete string match, but rather a prefix match.

There's also matches against lists of patterns for the User-Agent header to detect the type or size of the device, and that's usually a match against patterns, not fixed strings or prefixes, that are almost always not anchored.

The same goes for matches against various elements of the request for security whitelisting or blacklisting.

Committing a part of VCL to matches using bsearch and strcmp would strongly bias users toward the complete string match, even if that really doesn't fit their use case very well.

There's also the fact that while bsearch may seem to be a theoretically strong algorithm, it actually tends to be not very cache-friendly, due to the random access nature of poking around in the string table. And although binary searches are O(log n) in the number of string comparisons, the algorithm is obliged to iterate through every character in each string, at least until it finds a non-match, which other algorithms can avoid.

An alternative that might be a VMOD that implements tries, which only match characters in the strings up until they find a non-match or match -- it's O(k) where k is the length of the string to be matched. That can be more cache-friendly, and can also be used to match against prefixes.

Someone might develop a VMOD that matches against critbit trees, just like the algorithm that Varnish uses. That would probably be restricted to complete matches.

@nigoroll has some code kicking around that generates C code for a state machine, which is also O(k) in the length of the string to be matched, from a list of strings with glob-like wildcards. He's been telling me for a while that he'd like to add something like exactly you're proposing, except with the state machine code.

[Here](https://code.uplex.de/uplex-varnish/libvmod-re2) is a VMOD that integrates the Google re2 regular expression library, which has a Set interface that is amenable to matching against a long list of patterns. re2 also matches using state machines (meaning O(k) complexity), since re2 patterns are more strongly constrained than pcre patterns. In synthetic testing I've found that matches with the re2 Sets can be significantly faster then the if-elsif-elsif regex match idiom in standard VCL. And the re2 solution has the advantage that it's not constrained to fixed strings, fixed prefixes or glob wildcards (although not every possible pattern from pcre is legal in re2).

Why am I listing off all of this theoretical crap? To make the point that there are many use cases (complete matches, prefix matches, matches against patterns of various constrained forms), and many algorithms with competing advantages, and that's why we have VMODs. If VCL establishes a particular solution, then almost everyone will start using that, whether it's the best choice for them or not.

I agree with @gquintard that it would be better if VMODs were easier to integrate, so that people are less likely to push back against them. Although I'd point out that not everyone hosts their repos on github. %^)

About VCL_REGEX -- phk has indicated that this should really should also have been a VMOD solution (VMODs didn't exist at the time). For one thing, there are other choices for regex engines in the world besides pcre, as indicated above. Also, Philip Hazel is now maintaining pcre only for bugfixes, and all new development is being done for [pcre2](http://www.pcre.org/current/doc/html/pcre2.html). pcre can probably last for a while as the VCL regex engine, since it's likely to be a few years before pcre becomes intolerably obsolete, but it's bound to happen sooner or later. We'll have to think about how that will impact the Varnish project. No doubt phk has some ideas, at any rate I would hold off before elevating VCL_REGEX to a VRT type.

**Comment by slimhazard** [comment]
I realize that I'm overdoing this, but if I'm surveying all of the ways to match against lists of strings, I really should mention the blog series by @dhobsd (look at the posts from [2015](https://9vx.org/post/)), which studies even more algorithms in depth. A few of these are probably very good solutions to the standard Varnish problem of "match my Host header or URL prefix (or User-Agent or something else) against a list of strings". All the more reason to hand it off to VMODs.

**Comment by slimhazard** [comment]
OK, so I'm overdoing it. There's yet another dimension in the universe of choices, which is case sensitivity. @Dridi, for the use case that you've identified -- matching against the Host header -- it should at least be strcasecmp rather than strcmp. But in other situations, people will probably want and expect case sensitive matches.

**Comment by Dridi** [comment]
> I like the vcl as a minimal language, so I would be against. As you pointed, a vmod can easily do this.

Then we should move ACLs, probes and built-in functions (regsub, synthetic etc) to VMODs.

> I think the right answer to this request is to push back against the pushback.

I can't really do that, I wanted this kind of syntax ever since I encountered my first dilemma between a regex only I could decipher in my team at the time or opt for a series of if-elif statements that would make my inner-developer want to kill me in my sleep. That happened early, way before I landed my first patch in Varnish when I was simply "a user".

And even when I could finally point people to such a VMOD (thanks to @gquintard) they'd remind me that it doesn't appeal your average end-user.

> There's also the fact that while bsearch may seem to be a theoretically strong algorithm [...]

For the record, I didn't have the time to do better in a couple tube rides (which incidentally earned me a religious inquiry regarding my text editor). I really don't care about the performance here, I'm not sure whether a compiler could do better with an if-elif dance. The main use-case is to replace this kind of construct, a clean alternative.

Of course I'd be all for a more efficient implementation. I'm proposing a helpful feature here, not a best-of-breed implementation and if anyone can pull something better off in the 6.0 time frame, then great. Otherwise we can improve that later.

> About VCL_REGEX -- phk has indicated that this should really should also have been a VMOD solution

Ack. I don't think I was around when this was discussed.

> There's yet another dimension in the universe of choices, which is case sensitivity. @Dridi, for the use case that you've identified -- matching against the Host header -- it should at least be strcasecmp rather than strcmp.

I can't count the number of times I audited VCL and found incorrect host handling (I can count the opposite case, it's near zero). I'm doing this in the test case above, we are doing it in the docs. My favorite [1] is the use of a regular expression that over-matches because `.` has a special meaning.

However there's one place where I consistently hammer that you should normalize your host header and check it against known values (and reply a synthetic 404 if not known) and that place is the classroom. I always point people to `std.tolower`, and remind them that a domain name is indeed case insensitive.

If you really want to push the flexibility forward, then you can do this:

```vcl
table <name> [glob|regex] [case] {
    <list of static strings>
}
```

By default, you match static strings, you can switch to glob or regular expressions, and you can make any of the three case-insensitive. I went for the simple single case.

[1] 6b5242150f3e0a485c8e83d1fe1c4491acdc8105

**Comment by fgsch** [comment]
While I'd love to see changes in VCL I don't think this is a change I'd welcome.

Wether other parts of the current implementation should live in VMODs it's beside the point.

**Comment by Dridi** [comment]
Then we will put the last nail in the tables coffin during the bugwash.

**Comment by bsdphk** [comment]
I think the basic idea is great, but I want it in a vmod.

**Comment by nigoroll** [comment]
FTR I'd consider https://code.uplex.de/uplex-varnish/libvmod-re2 with `re2.set` a replacement for this and @slimhazard is working on more improvements in particular for associating matches with other things.
