### ISSUE TITLE
2018-03 Release Coordination

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2438]
This ticket is for coordination of the March 2018 release.

# Desirable content of this release:
* Clear separation of VMOD API levels in .h files (phk)
* VCL object model nailed down (phk)
* ~~VCL-configurable VFP/VDP stacks (phk)~~
* UNIX domain sockets (geoff)
* VMOD VSC counters (dridi/phk)
* Better everything (everybody)

# Things people want to see improved, without putting their name on the line:
* H2

# Things for discussion:

## VCL identifiers case-sensitive (... 5.1) or not (-trunk)
  * HTTP headers are not case sensitive, so req.http.foo and req.http.FoO are the same anyway.

## Horrible director/backend naming in C name-space
  * Time to change backend → http_backend and director → backend ?

# TODO list for release

## Document #2521 issue in release note

**Comment by nigoroll** [comment]
bugwash:
* do we want to retain strict 4.0 vcl semantics? See for example #2509 or c2406f4ff586b7f00efb86d06a250ec249f6f53d

**Comment by nigoroll** [comment]
during last bugwash we agreed that we wanted to ponder this. Here's my bit:

general thoughts:
* if we aim to keep semantics for existing vcl, we might still fail by introducing new bugs (for instance in wrapper code)
* we would not want to maintain current semantics indefinitely, so the only benefit for users would the option to delay migration of their vcl
* this endeavor diverts resources from making actual progress
* how many vtcs would we need to double?
* would we need to duplicate all vmods?
* Do bundled vmods count towards vcl semantic compatibility? If we tell users "you will be able to keep your vcl", they would expect this to include vmods, right?

code:
* gc beresp.storage #2509 
  * could keep old code or
  * implement wrapper to retain old behavior
  * is this relevant at all? Worth the effort?
* change restart handling c2406f4
  * would need to keep two code paths in core
* backend connection recycle/retry #2135
  * would not make sense to optionally switch back to old behavior, IMHO
* doesn't VRT_fail break existing semantics?

my opinion:
I understand that we have upset some users in the past by requiring work on VCL changes, but my impression is that this was mainly caused by the client/backend separation and a number of renames. I do not see much value in diverting developer resources to developing and maintaining a compatibility layer for something like "the last two major version's VCL semantics": The benefit appears rather minor and there is a risk of failing on details.
If anything, we should support work similar to @fgsch 's vcl converter https://github.com/fgsch/varnish3to4 and invest into better documentation and migration guides.

**Comment by Dridi** [comment]
Hi @nigoroll,

Below is my interpretation of the backwards compatibility question, based on mental notes I've taken over time. I don't necessarily disagree with your views (except for some nitty-gritty details) but this should give more context.

> if we aim to keep semantics for existing vcl, we might still fail by introducing new bugs (for instance in wrapper code)

We can't promise not to have bugs, so we should only talk about breaking things _on purpose_ IMHO.

> we would not want to maintain current semantics indefinitely, so the only benefit for users would the option to delay migration of their vcl

I believe this applies to `vcl 5.0`, when it happens. It could be Varnish 6.0 of course if we change our minds.

> this endeavor diverts resources from making actual progress

This was a decision made at least a year and a half ago: c0c1e051151875b0914f479a5ebccdaff435986.

Again, we can always change our minds, but to me it looks like a conscious decision to risk diverting resources in favor of "VCL stability" to avoid too frequent "4.0 situations".

> how many vtcs would we need to double?

In theory, none. Because `vcl 4.1` code could include `vcl 4.0` code, or Varnish could simply `vcl.load` old code: we'd only need to test 4.1-specific code and maybe teach `varnishtest` when to use which version. (And keep the default to 4.0?)

> would we need to duplicate all vmods?
>
> Do bundled vmods count towards vcl semantic compatibility? If we tell users "you will be able to keep your vcl", they would expect this to include vmods, right?

When we discussed the API breakages in vmod-std between the 4.0 and 4.1 series @bsdphk said that `vcl 4.0` should encompass VCL itself and built-in VMODs. Meaning that out-of-tree VMODs/VRT can break, and they always do on major releases.

> gc beresp.storage #2509

I already pointed out that we can remove `storage_hint` from core code and maintain its existence in `vcl 4.0`.

> change restart handling c2406f4
> [...]
> backend connection recycle/retry #2135 

I'd consider the restart handling as a bug fix, and the retry bug is about core code and not VCL.

> doesn't VRT_fail break existing semantics?

Not sure to understand, but if it's VRT then it's not part of `vcl 4.0`.

> If anything, we should support work similar to @fgsch 's vcl converter https://github.com/fgsch/varnish3to4 and invest into better documentation and migration guides.

But that would only solve the "major bump" problem if we abandon `vcl 4.1` and go directly to `vcl 5.0`. Don't get me wrong, I'd rather have something like that in-tree if we can reasonably maintain it.

**Comment by nigoroll** [comment]
Quick reply to @Dridi 

> We can't promise not to have bugs, so we should only talk about breaking things _on purpose_ 

my concern are additional bugs which only get introduced due to the multi vcl version support.

> > doesn't VRT_fail break existing semantics?

> Not sure to understand, but if it's VRT then it's not part of `vcl 4.0`.

varnish now behaves very differently in error situations and this could be an issue if users expect `vcl 4.0` to be fully compatible.

**Comment by Dridi** [comment]
> my concern are additional bugs which only get introduced due to the multi vcl version support.

Like I said, I don't necessarily disagree.

> varnish now behaves very differently in error situations and this could be an issue if users expect `vcl 4.0` to be fully compatible.

If you are referring to `VRT_fail` kicking in when you set an empty URL or similar changes, I'd consider them bug fixes.

**Comment by Dridi** [comment]
I just remembered that we broke `vcl 4.0` by turning symbols from case-sensitive to insensitive. We should mention that in the release notes.

Not all the core code is aware of that:

```
varnishtest "case-incensitive default backend"

server s1 {
        rxreq
        txresp -status 500
} -start

server s2 {
        rxreq
        txresp
} -start

varnish v1 -vcl {
        backend s1 { .host="${s1_sock}"; }
        backend Default { .host="${s2_sock}"; }

        sub vcl_init {
                if (s1 != default) { }
        }
} -start

varnish v1 -cliok "backend.list *"

client c1 {
        txreq
        rxresp
        expect resp.status == 200
} -run
```

And I wonder how many of the CLI and VSM consumers will cope with that change out of the box.

**Comment by slimhazard** [comment]
> * VCL-configurable VFP/VDP stacks (phk)

Currently it's not possible to replace the builtin ESI VDP with another VDP for ESI from a VMOD (say for parallel ESI). This is because ``VDP_ESI`` gets ``VDP_push``ed in ``cnt_transmit``, which gets called after ``vcl_deliver``, so there's no way to arrange for a VMOD call that pushes a "substitute" VDP for ESI. The same would also be true of a VMOD that wants to implement its own VDP for gzip (maybe for compression in general, say a brotli VDP).

There's a trick that _almost_ works -- setting ``req->disable_esi`` to true when the alternative VDP for ESI is pushed. If it had worked, the VMOD would have had to document "don't ever set ``req.esi`` to true after making the VMOD call, otherwise the results are undefined"; and there's also the matter that ``req.esi`` is currently documented as deprecated and subject to change in a future release, which might mean that ``req->disable_esi`` could go away as well.

But it doesn't work anyway, because pushing ``VDP_ESI`` in ``cnt_transmit`` resets ``req->resp_len``, which had been set to the content length earlier in ``cnt_transmit``. This has the effect later on of unsetting ``Content-Length`` and (for HTTP/1) getting ``Transfer-Encoding: chunked`` set, which is necessary for a client to read the response.

So pushing a VDP for ESI in ``vcl_deliver``, even if it also resets ``resp_len``, will end up with a malformed response, because ``resp_len`` gets set to the content length afterward in ``cnt_trasmit``, and there's no way for a VMOD to reset it again, in order to get the proper response headers for transfer.

What's our status on this feature? Are we still going for it for March? In that case, do I need to think about how the VDPs for ESI and gzip get managed in ``cnt_transmit``, or is that likely to change into something that a VMOD can affect? (I am aware of @rezan's submissions about the topic on -dev).

Assuming that the ESI and gunzip VDPs will continue to have a special status in the future, I think a way to handle this would be to have ``vdp_bytes`` pointers in ``struct req``, which default to ``VDP_ESI`` and ``VDP_gunzip``:
```
struct req {
        // ...
        vdp_bytes esi_vdp;
        vdp_bytes gunzip_vdp;
        // ...
};
```
Then ``cnt_transmit`` may push the VDPs as it does now, but it pushes ``req->esi_vdp`` and/or ``req->gunzip_vdp``. If they are not changed, everything works as before, but it may push VDPs that a VMOD has replaced.

Then the rule for authors of VDPs in VMODs would be: if you're implementing a new VDP entirely (say for regex substitution or whatever), then VDP_push it; if you're implementing substitute versions of ESI or gunzip, set the ``vdp_bytes`` pointers in ``req``. (A VRT function could do that for you.)

**Comment by slimhazard** [comment]
Another issue with a VDP VMOD for ESI is that not even ``$ABI strict`` and building against a Varnish source tree appears to be enough to access the functions it needs to use, without resorting to another "trick". ``cache_esi_deliver.c`` calls ``THR_SetRequest`` and ``VRTPRIV_dynamic_kill``, neither of which are available in ``cache.h`` -- you have to compile with ``-DVARNISHD_IS_NOT_A_VMOD``, obviously a "sin" for a VMOD.

I think a VMOD that implements its own VDP processing will need to use both of those functions. After ESI subrequest processing, PRIV objects will have to be finalized, otherwise there may be resource leaks. ``THR_GetRequest`` is currently called for panic messages, so unless ``THR_SetRequest`` gets set properly, a panic message will emit incorrect information about the request involved in the panic. If setting the request object per thread ever gets used for purposes besides panic messages, it becomes all the more critical, particularly if the req is sent off to another worker thread for parallel ESI.

The VMOD code I'm currently puttering with uses a modified version of ``cache_esi_deliver.c``, and many long stretches from there would never be changed. For the most part, ``ved_include`` is all it needs to modify. I certainly wouldn't touch any of the code that integrates ESI with gzip. That would mean that VMOD development for a VDP ESI would have to keep up with changes to ``cache_esi_deliver.c`` in core over time.

I don't see an easy way to avoid that, but if we want to encourage VDP development for ESIs, it would be easier if the core ESI VDP were modularized a bit more, so that a VMOD author doesn't have to copy as much from core. There are more possibilities for VMODs in addition to parallel ESI -- someone might want to implement more ESI features, such as variables, conditions and error handling, so I think there's value for the project to make it easier to do.

**Comment by fgsch** [comment]
March is in the past.
