### ISSUE TITLE
vmodtool should not output PRIV_VCL in RST

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2448]
as in:

`new OBJ = constructor(PRIV_VCL)`

**Comment by fgsch** [comment]
IIUC this will remove all PRIV_XXX from the docs.
So how one knows when a method/functions operates at PRIV_VCL, PRIV_CALL, etc?

**Comment by nigoroll** [comment]
From the VCC file?

My understanding is that the .rst we generate is for vcl authors, who are not concerned with whatever PRIV varnish passes internally and, in particular, previously needed to understand that the PRIV arguments are nothing to pass from VCL.

**Comment by slimhazard** [comment]
@fgsch one would know about it if there is written documentation that explains how it works.

It's always seemed to me that the auto-generated RST docs are strongly biased towards readers who are familiar with the inner workings of VMODs. You and I and @nigoroll know what PRIV_XXX are, and we know to look into the VCC or C sources. But if a reader who doesn't know about these things sees PRIV_XXX in the documented prototype, I don't see how he or she becomes any more enlightened.

If a VMOD author doesn't bother to document the implications of PRIV-scope, I don't think we can or should hold their hands so much as to try to fix that for them.

While we're on the subject, I don't much like the way that the auto-generated prototypes display default values for parameters. A VMOD method or function might have something like this:
```
VIOD foo(STRING str=0, BOOL bool=0, ENUM {foo, bar} en=0)
```
... because the '0' in each case works for the C type: NULL for the STRING, and also for the ENUM (since ENUMs are actually strings), and ``unsigned`` for the BOOL. But each one of these looks like a data type error: 0 is not a VCL string, boolean or enum.

**Comment by fgsch** [comment]
Except that we removed it and did not offer a replacement.

While I agree that by itself does not explain what it meant, people could search for it if they were inclined to do so.

**Comment by nigoroll** [comment]
My take on this is that having the PRIVs in the user documentation was wrong to begin with, so there is nothing to replace.
People searching for the PRIV could search for it in the vcc file or, if the vcc author considered the information relevant, she would have provided appropriate information.
Again, this is user documentation, so I completely fail to understand your point.

**Comment by Dridi** [comment]
> ... because the '0' in each case works for the C type: NULL for the STRING, [...]

Since the next release should include at least `stddef.h` VMOD authors will be allowed to put `NULL` as a default value from then on (also applies to other types like backends, probes or ACLs).
