### ISSUE TITLE
Test tests/r02429 fails on ppc64 and ppc64le

### ISSUE THREAD

**Issue by ingvarha** [varnishcache/varnish-cache#2496]
tests/r02429 fails on ppc64 and ppc64le.

https://kojipkgs.fedoraproject.org//work/tasks/336/23150336/build.log
https://kojipkgs.fedoraproject.org//work/tasks/82/23150082/build.log

This stops clean patching of CVE-2017-8807 on Fedora.

Ingvar

**Comment by mbgrydeland** [comment]
This was surprising to me. The test case isn't very exotic, so I see no reason for it to fail.

Comparing to other similarish test cases that I see from your build logs, there is one possible culprit. The other test cases using -sfile have a size of the storage of 10m, while I opted for 1m. May be because of some rounding things 1m is just too small a file?

Would you be able to test if:
```diff --git a/bin/varnishtest/tests/r02429.vtc b/bin/varnishtest/tests/r02429.vtc
index 02c8450..81e42f0 100644
--- a/bin/varnishtest/tests/r02429.vtc
+++ b/bin/varnishtest/tests/r02429.vtc
@@ -4,7 +4,7 @@ server s1 {
        accept
 } -start
 
-varnish v1 -arg "-s Transient=file,${tmpdir}/_.file,1m" -vcl+backend {
+varnish v1 -arg "-s Transient=file,${tmpdir}/_.file,10m" -vcl+backend {
        sub vcl_backend_error {
                synthetic("foo");
                return (deliver);
```
does the trick?
