### ISSUE TITLE
bring back beresp.storage_hint

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2509]
Opening ticket as a bugwash reminder

My commit e1535c8d14aa9b7a796b426101780e7237e8ab97 triggered some discussion on -commit. Basically, my assumption was that we are already heading for a major release with breaking changes and because I will need to touch `(struct busyobj).storage` soon, I just wanted to get the already deprecated field `storage_hint` out of the way.

Summary of feedback & my responses:
* @Dridi: _is this in line with our aim to keep 4.0 syntax?_
  * I think so, removal of deprecated fields is a process orthogonal to syntax
* @fgsch had planned to keep `storage_hint` until after 6.0
  * why would we not clean up for the next major release, but rather the second next? What would be the advantage?

**Comment by Dridi** [comment]
Technically, my remark was about a planned minor bump of vcl to 4.1 that implies not breaking the vcl 4.0 syntax. So deprecated or not we can't get rid of it unless we do a major vcl 5.0 bump. We could however ditch it from `struct busyobj` if we teach vcc&vrt how to bridge the gap with `beresp.storage_hint`.

**Comment by nigoroll** [comment]
wasn't the purpose of the vcl marker to avoid issues due to ambiguities? I am not sure if we ever defined this properly, but - again - I thought that breaking changes in vcl would not require a vcl bump, but rather only a version bump. For example, in 9552aa16b46b38b0b3eb7ac42f3bc6295f50eecc we removed a return option without bumping vcl.

**Comment by fgsch** [comment]
Guilty as charged.

To clarify, I'm not against removing these but simply when I added bereq.storage IIRC we decided to keep these around until after 6.0.

There was no discussion (that I can remember), or policies for the matter, when I GC the action.

Perhaps we should define the policy going forward to avoid ambiguities in the future.

**Comment by Dridi** [comment]
@nigoroll there's a difference between breaking, and breaking on purpose. For example we "broke" vcl 4.0 between Varnish 4.0 and 4.1 via vmod-std.

My reply to the commits list was not opinionated, I'm simply pointing out the breakage and although I can't find a reference I'm pretty sure @bsdphk said we would bump vcl to 4.1 and still allow `vcl.load`'ing or `include`'ing vcl 4.0 code.

And again, I have nothing against removing this from the structure, and it's trivial to keep the behavior of `beresp.storage_hint` because storage backends are static so we don't need to keep the string around to later resolve a storage.

**Comment by nigoroll** [comment]
the bugwash voted to bring back compatible `backend_hint`.
