### ISSUE TITLE
failing u tests on solaris

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2537]
ticket so I don't forget

> (16:23:06) phk: slink, geoff if any of you can take a peek on u0000::p2 on solaris I would appreciate it.  The problem is almost certainly the failure of the two ioctls (TIOCWINSZ, TCSAFLUSH)

**Comment by slimhazard** [comment]
`isatty(fd)` is returning false for the fd passed into `process_init_term()` -- is that the problem? Sorry that I have next to no experience with termio, but it might explain why the ioctls are being rejected with `EINVAL` -- the invalid argument is not the ioctls, but rather the file descriptor.

Other than that, I can't see what the problem is. `TIOCSWINSIZ` is documented in man `termio(7I)` on our Illumos machine as the ioctl to set the window size via a pointer to `struct winsize`, which has the same fields that I see in the man page on my Debian laptop. `TCSAFLUSH` is documented in man `tcsetattr(3C)` as an "optional parameter", also exactly as I see it in the man page on my laptop.

The fd is obtained in `process_start()` by `open(2)`-ing the "slave ptty" returned by `ptsname(3)`. I'll keep looking to see if this works differently on SunOS somehow.

**Comment by slimhazard** [comment]
`isatty(master)` is also returning 0 for the master fd returned from `posix_openpt()`.

**Comment by slimhazard** [comment]
This patch gets the test to pass (along with the rest of make check):
```
diff --git a/bin/varnishtest/vtc_process.c b/bin/varnishtest/vtc_process.c
index d7b94e6..1439af3 100644
--- a/bin/varnishtest/vtc_process.c
+++ b/bin/varnishtest/vtc_process.c
@@ -40,6 +40,7 @@
 #include <string.h>
 #include <termios.h>
 #include <unistd.h>
+#include <stropts.h>
 
 #include "vtc.h"
 
@@ -334,7 +335,7 @@ process_init_term(struct process *p, int fd)
        tt.c_cc[VKILL] = '\x15';                // CTRL-U
        tt.c_cc[VINTR] = '\x03';                // CTRL-C
        tt.c_cc[VQUIT] = '\x1c';                // CTRL-backslash
-       tt.c_cc[VMIN] = 1;
+       //tt.c_cc[VMIN] = 1;
 
        i = tcsetattr(fd, TCSAFLUSH, &tt);
        if (i)
@@ -366,6 +367,10 @@ process_start(struct process *p)
        AN(slavename);
        slave = open(slavename, O_RDWR);
        assert(slave >= 0);
+       if (ioctl(slave, I_PUSH, "ptem"))
+               vtc_log(p->vl, 4, "PUSH ptem: %s", strerror(errno));
+       if (ioctl(slave, I_PUSH, "ldterm"))
+                vtc_log(p->vl, 4, "PUSH ldterm: %s", strerror(errno));
 
        process_init_term(p, slave);
 
```
man `termio(7I)` says: "The  VMIN element is the same element as the VEOF element; ...", so the assignment `tt.c_cc[VMIN] = 1` had the effect of setting the EOF control character to `\x01`. I haven't heard back from phk about what he wanted to accomplish with the VMIN assignment.

The `ioctl(I_PUSH)` calls are required by Solaris STREAMS to push down the `ldterm` and `ptem` modules, so as to handle `ioctl()` calls for pseudo-TTYs. See the [docs](https://docs.oracle.com/cd/E26502_01/html/E35856/termsub15-44781.html) and some [sample code](http://poincare.matf.bg.ac.rs/~ivana/courses/ps/sistemi_knjige/pomocno/apue/APUE/0201433079/ch19lev1sec3.html) (code in section 19.3.1). `stropts.h` is needed for `I_PUSH`.

So we'll have to clarify:
* Can we remove the VMIN assignment?
* How should we handle the platform-dependent code (`#include <stropts.h' and the `ioctl(I_PUSH)` calls)? Surround those lines with `#if defined (__sun)`?

**Comment by nigoroll** [comment]
@bsdphk @slimhazard close?

**Comment by bsdphk** [comment]
Yes, this seems to work now.

Thanks a LOT for your help Geoff.
