### ISSUE TITLE
backend connection keepalive on pass  needs to force bereq.proto

### ISSUE THREAD

**Issue by ehocdet** [varnishcache/varnish-cache#2574]
about #2566, this use case needs to keep bereq.proto writable (run on master branch):

```
varnishtest "varnish to backend keepalive on pass"

server s1 {
        rxreq
        expect req.proto == HTTP/1.1
        txresp
} -start

varnish v1 -vcl+backend {
        sub vcl_recv {
            return (pass);
        }
        sub vcl_backend_fetch {
#           set bereq.proto = "HTTP/1.1";
        }
} -start

client c1 {
        txreq -proto HTTP/1.0
        rxresp
        expect resp.http.connection == close
} -run

```

. without `return (pass);` test is ok
. with  `return (pass);` test fail,  `set bereq.proto = "HTTP/1.1";` is needed

**Comment by bsdphk** [comment]
I must admit that I thought we already changed it so that Varnish always (ie: non-pipe) sends HTTP/1.1 to the backend, and I think that is the correct fix here.

The restatement in RFC7230 2.6 makes it clear that the protocol field in a **request** is not what the sender is expecting the response to be, but what the sender itself is prepared to speak.

**Comment by bsdphk** [comment]
Bugwash conclusion:  Always send HTTP/1 to backend, except for pipe.
