### ISSUE TITLE
Request for a stable header file for VMODs

### ISSUE THREAD

**Issue by SpikesDivZero** [varnishcache/varnish-cache#2584]
It looks like the include order seems to change somewhat regularly, and that the include order can be pretty sensitive. For example:

Release 4.1:
https://github.com/varnishcache/libvmod-example/blob/4.1/src/vmod_example.c#L4-L6

Release 5.2:
https://github.com/varnishcache/libvmod-example/blob/5.2/src/vmod_example.c#L6-L9

Upcoming 5.3:
https://github.com/varnishcache/libvmod-example/blob/a17fb592b1b0e0857e9e883c7708241ab0b4465e/src/vmod_example.c#L6-L8

And the notes for trunk specifically call out "some headers require specific include ordering".
https://github.com/varnishcache/varnish-cache/blob/5f5185e8acd65f881c690bfdbf30fd5f49e16ad1/doc/changes.rst#c-apis-for-vmod-and-utility-authors

This seems to suggest that if we want to target >= 5.0, VMOD authors and maintainers need to have our own header with some preprocessor macros to ensure everything works across versions.

Would it be possible to get a single header file for VMOD authors to include in order to get the "essentials"? (I'll leave the question of what constitutes "essentials" to your discretion.)

I tried to search for any other similar requests, but didn't see one off hand. Apologies in advance if this is a duplicate.

**Comment by Dridi** [comment]
The reason why you didn't see a similar request is because we use the issue tracker for bugs only, as explained in the issue template. This is material for either the IRC channels or one of the mailing lists.

It sucks, but the change was made in order to stabilize the VMOD interface in the long run. Here is how I deal with it:

https://github.com/Dridi/libvmod-querystring/blob/9f4a3564fe8d1845b07b6d3741ed5c48443f4d6e/src/vmod_querystring.c#L26-L36
