### ISSUE TITLE
request body straight insufficient bytes with EAGAIN

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2629]
Does EAGAIN actually fail a request? Or is the error message bogus?

```
-   ReqMethod      POST
...
-   VCL_return     fetch
-   Link           bereq 760157720 pass
-   Storage        malloc Transient
-   FetchError     Resource temporarily unavailable
-   FetchError     straight insufficient bytes
-   Timestamp      ReqBody: 1521479617.568399 45.745452 45.745452
-   Timestamp      Fetch: 1521479631.765802 59.942856 14.197403
...
--  BackendStart   I.I.I.I P
--  FetchError     req.body read error: 11 (Resource temporarily unavailable)
--  FetchError     backend write error: 11 (Resource temporarily unavailable)
--  Timestamp      Bereq: 1521479617.568445 45.745316 45.745316

```

**Comment by slimhazard** [comment]
This has been around in one form or another since at least Varnish 3.x. The actual problem here is a problem reading the _client_ request body (timeout, for example, results in EAGAIN).

But reading the client request body and passing the bytes along to the backend request happens in a loop during fetch (unless the client request body was cached). So it's an error that happens during fetch, and hence gets logged as a `FetchError`. Since it's happening during the loop that writes to the backend, Varnish logs something about a `backend write error`, even if the problem has nothing to do with writing to the backend.

I've seen this many, many times, and believe it possible that it never, not once, had anything to do with the fetch or the backend. But rather always some kind of hangup or timeout or cancel on the part of the client (which of course can happen all the time).

@nigoroll, this and #2628 get into something that's been on my mind for a while. `FetchError` is one of the most important diagnostics we have (especially in the situations where backend devs are saying "it must be Varnish's fault, now you go prove to me that it isn't"). We can use a lot of improvement in the `FetchError` error reporting.

**Comment by bsdphk** [comment]
Agree on improving FetchError.  Do we also need a ClientError ?

**Comment by slimhazard** [comment]
`ClientError` would be a good idea. A `FetchError` is usually a problem within a project that needs to be addressed, whereas errors on the client side are often a fact of life that can be reasonably ignored. The log would help a lot by pointing out the difference.

**Comment by Dridi** [comment]
@slimhazard or at the very least correlate a `ClientError` with a `FetchError` if there are situations where the former can cause the latter (eg. when there is a `req.body`?)

**Comment by bsdphk** [comment]
Improving error messages welcome, doesn't need tickets.
