### ISSUE TITLE
Wrong turn at cache/cache_backend_probe.c:255: Unknown family

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2702]
See also #2151 and #2244.

```vcl
varnishtest "unix proxy"

server s1 "" -start

varnish v1 -proto PROXY -arg "-a ${tmpdir}/v1.sock" -vcl+backend {
        sub vcl_recv {
                # XXX: needs a relevant condition, this is broken logic
                if (client.ip != remote.ip || server.ip != local.ip) {
                        return (synth(400));
                }
                return (synth(200));
        }
} -start

varnish v2 -vcl {
        probe default {
                .window = 1;
                .initial = 1;
                .threshold = 1;
                .interval =0.5s;
        }

        backend v1 {
                .path = "${tmpdir}/v1.sock";
                .proxy_header = 1;
        }
} -start

client c1 -connect ${v2_sock} {
        txreq
        rxresp
        expect resp.status == 200
} -run

delay 1

varnish v2 -cliexpect "vcl1.v1[ ]+probe[ ]+1/1[ ]+good" backend.list
```

Setting `.proxy_header = 2` fails in different interesting ways.

**Comment by slimhazard** [comment]
@Dridi the first versions of the patch to add UDS had some code for handling AF_UNIX in the proxy protocol, but none of that made it into the 6.0 release. For one thing, nobody seemed to be asking for it (and was down to just days before the release date before @bsdphk was comfortable adding any of the rest). It also opens various cans of worms.

PROXYv1 doesn't support AF_UNIX -- it's either IPv4, IPv6 or PROXY_UNKNOWN. I think we could have a better solution than asserting WRONG() if it's neither of the IP families by having a way to handle PROXY_UNKNOWN, and then all of the *.ip variables be will have bogo-IP value. But there's not much else we can do for UDS and PROXYv1, since the protocol version doesn't handle it.

PROXYv2 does support AF_UNIX, but that gets us into a problem area for which I, for one, never could think of a good solution. Addresses passed on via PROXY are currently stored as session attributes in session workspace; that's where IP addresses from PROXY go. But UDS addresses in session workspace (struct sockaddr_un) is precisely what @bsdphk wanted most to avoid, because of their size; almost everything about the design of the UDS solution centered around avoiding that.

If we put UDS addresses from PROXY into session workspace after all, as we do with the IP addresses from PROXY, then it undoes everything we were trying to do with UDS in the first place. (Note that the PROXY could conceivably send two of them.)

I can see why it would be highly wasteful, since the UDS address sent via PROXY is likely to be the same all the time for a very long time during a deployment (until someone changes the address, which may not happen for days, weeks, months ...). So we'd be using up all that session workspace just to say the same thing all the time.

That suggests the idea of having an external table of addresses, and having session attributes that point to addresses in the table (that's an idea we were considering for UDS for a while). Most likely there would only be a few addresses at a time. But then something would have to clean up the table occasionally, if an address is eventually not being re-used after all.

So that's what I mean by "can of worms". As it is, I really don't have a good idea for what to do about UDS addresses sent via PROXY.

OTOH I think it should be fairly easy to *send* UDS addresses to backends via PROXYv2. (For PROXYv1, it will always be UNKNOWN, but I believe we already have that.) I probably still have some code in one of the fork branches that does that.

**Comment by Dridi** [comment]
> PROXYv1 doesn't support AF_UNIX -- it's either IPv4, IPv6 or PROXY_UNKNOWN. I think we could have a better solution than asserting WRONG() [...]

Agreed, it should be PROXY_UNKNOWN. But in this case it's not just the probes that should handle that case but the listen side of things too.

> If we put UDS addresses from PROXY into session workspace after all, as we do with the IP addresses from PROXY, then it undoes everything we were trying to do with UDS in the first place.

On the other hand if someone expects PROXY headers they inherently trust the client in front of them so they could tweak `workspace_session` accordingly if they should expect UDSs to be passed via PROXYv2?

> That suggests the idea of having an external table of addresses, and having session attributes that point to addresses in the table (that's an idea we were considering for UDS for a while). Most likely there would only be a few addresses at a time. But then something would have to clean up the table occasionally, if an address is eventually not being re-used after all.

Oh noes, a cache! How do we invalidate it? :-p

> OTOH I think it should be fairly easy to *send* UDS addresses to backends via PROXYv2. (For PROXYv1, it will always be UNKNOWN, but I believe we already have that.) I probably still have some code in one of the fork branches that does that.

Either we do that, or we clearly make listening to a UDS and backends non-zero `.proxy_header` mutual exclusive in libvcc and wait until someone complains about the missing feature. That doesn't solve the case where we listen to TCP+PROXYv2 and receive a UDS from upstream (though we forward bogo 0.0.0.0:0 endpoints in that case).

I think in general we might need more PROXY coverage to see what we get for all cases and then we can decide how to handle each corner case.

**Comment by nigoroll** [comment]
bugwash discussion summary:
* will be left for @slimhazard to look after when he's back
* consensus was that for the AF_UNIX case we should just lie about the address information when forwarding to backends, at least for now
* haproxy willy should be asked for guidance on what to send for AF_UNIX on proxyv1, ideas:
** TCP4 0.0.0.0
** TCP4 127.0.0.[12]

**Comment by slimhazard** [comment]
I won't be doing anything for this until I get back in two weeks. But I'd like to comment for now that I don't understand the summary.

* There's a hard part to this, as discussed above, but AFAICT the summary has nothing to say about it.
* There's an easy part, with an obvious solution that is correct and that we could implement right now. But the summary says that we shouldn't do that, and the only reason given is that it was the consensus at bugwash.
* Not only that, it says that we should implement a "lie" for the easy part. That sets us up for an incompatible change at some point in the future, should we decide to go for the obvious and easily implemented solution after all.

The two parts of PROXY and UDS are:
* What to do if we have ``-a PROXY``, and the forwarding component sends a UDS address via PROXYv2, or PROXY_UNKNOWN (which is possible with both PROXY versions, and is the only value could get via PROXYv1 for an non-IP address).
* What to do if we have a backend with a ``.proxy_header`` setting, and the address to be forwarded is UDS.

The ``-a`` case is the hard part, because addresses received via PROXY are stored in session workspace, which is precisely what we didn't want to do with ``struct sockaddr_un``. Tbh I can't tell from the summary whether this case was discussed at bugwash at all.

There's also the matter that we could do better than crashing on assert if we receive PROXY_UNKNOWN. We'd have decide what to do with ``client.ip`` and ``server.ip`` for PROXY_UNKNOWN -- set them to the bogo-IP, or leave them equal to ``remote.ip`` and ``local.ip``? (IMO that decision could go either way, but it's not the hardest decision we've ever had to make.)

If a backend has ``.proxy_header`` and the address is UDS; we can do this:
* For ``.proxy_header = 1``, send PROXY_UNKNOWN.
* For ``.proxy_header = 2``, send the UDS address in the proxy header.

It's my fault for not attending bugwash, so I don't know the reasons for preferring a "lie", but there's no technical reason why we can't do it this way.

If we "lie" now, and then someday want to implement the solution above instead, then we'll be introducing an incompatible change. We might even have to change the major version number. But just for that? Seems to me that we'd be better off doing it right the first time.

BTW, sending a UDS via PROXY to a backend can only happen if ``-a`` _doesn't_ use PROXY but _does_ use a UDS address. If we have ``-a PROXY`` and get IP addresses for ``client.ip`` and ``server.ip``, we just send those -- I believe that is already working now.

Theoretically, it could also happen if we have ``-a PROXY`` and a UDS address is received via PROXY, but then we'd have to have a solution for the first problem that retains the UDS address. This case is probably very unlikely, since it's hard to imagine a deployment with a chain of PROXYs where the first address in the chain is a UDS -- most setups will want to have a public network address, after all.

**Comment by bsdphk** [comment]
Bugwash conclusion (1):  If -a receives Proxy2 with UDS, we just ignore it and fall back to remote.*

**Comment by bsdphk** [comment]
Bugwash conclusion(2):  Geoff produces patch for backend side of things
