### ISSUE TITLE
varnishtest -> vtest

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2752]
After the 6.1 release I would like to split varnishtest out to be its own project named 'vtest'.

This will level the playing field for other projects who use varnishtest now, and will allow vtest development to proceed at its own terms, and with its own release cycle.

The (im)practicalites of the split remains to be seen.

**Comment by fgsch** [comment]
I think this is a great idea and something I've needed and thought about in the past.
I'm not sure about the naming but I like my shed blue.

**Comment by bsdphk** [comment]
There's a couple of sane-ish reasons for the name.

1. We don't want to force other proxies to type "varnish" all the time, that will only make them hate us.

2. I've always regretted the amount of typing myself.

3. vtest retains the .vtc file suffix.

4. It's sort of in spirit of apache-bench -> ab

**Comment by Dridi** [comment]
I have this bucket of paint from my recent move and until now I had no idea where to use it :p

For the vtest name, I find it confusing rather than sane since we already have something called vtest. I also don't like typing the same thing over and over again so for that I have aliases (for example I can type `git ap` for `git add -p`).

Next, I think we should keep `varnishtest` in this project, and instead move its guts in its own shiny project. Call it `libvarnishtest` or `libvtc` for example.

Then we can have the library as a dependency, and keep building `varnishtest` as we do today to use it the way we do today as part of our test suite. For this to work, the library needs to ship the agnostic commands (`client`, `server`, `process`, `barrier`, etc) and be configurable (read "add custom commands and macros"). In our case the configuration would happen once in `varnishtest`'s main process, and then a test case would be run via the library for each fork.

Interested parties may not be interested in a command line interface and may integrate it differently. They could add commands in addition to the ones the library would ship (eg. we keep our `varnish` and `logexpect` "custom" commands in this tree and the HAProxy folks can maintain their integration the way they see fit).

This would also be the occasion to better frame a syntax for commands, and get rid of inconsistencies. Unfortunately that also means breaking the syntax. If we start this work after 6.1, we can also decide to flip the switch and break the vtc syntax for 7.0.

I have such a prototype (embryo) and if that's relevant I could try to present it during the next VDD. But I could (maybe-really-really-not-sure) only attend the afternoon.

**Comment by bsdphk** [comment]
This subject now lives in the vtest githup repos.  Closing here.

**Comment by lkarsten** [comment]
https://github.com/vtest/VTest
