### ISSUE TITLE
b64.vtc unstable

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2753]
seems like what is happening here is that the bgfetch is overtaken by c3
```
15:11:48 **** c3    1.9 rxhdr|HTTP/1.1 200 OK\r
15:11:48 **** c3    1.9 rxhdr|Content-Length: 1\r
15:11:48 **** c3    1.9 rxhdr|Date: Thu, 30 Aug 2018 13:09:27 GMT\r
15:11:48 **** c3    1.9 rxhdr|X-Varnish: 1006\r
15:11:48 **** c3    1.9 rxhdr|Age: 0\r
15:11:48 **** c3    1.9 rxhdr|Via: 1.1 varnish (Varnish/6.0)\r
15:11:48 **** c3    1.9 rxhdr|Accept-Ranges: bytes\r
15:11:48 **** c3    1.9 rxhdr|Connection: keep-alive\r
15:11:48 **** c3    1.9 rxhdr|\r
15:11:48 **** c3    1.9 rxhdrlen = 178
15:11:48 **** c3    1.9 http[ 0] |HTTP/1.1
15:11:48 **** c3    1.9 http[ 1] |200
15:11:48 **** c3    1.9 http[ 2] |OK
15:11:48 **** c3    1.9 http[ 3] |Content-Length: 1
15:11:48 **** c3    1.9 http[ 4] |Date: Thu, 30 Aug 2018 13:09:27 GMT
15:11:48 **** c3    1.9 http[ 5] |X-Varnish: 1006
15:11:48 **** c3    1.9 http[ 6] |Age: 0
15:11:48 **** c3    1.9 http[ 7] |Via: 1.1 varnish (Varnish/6.0)
15:11:48 **** c3    1.9 http[ 8] |Accept-Ranges: bytes
15:11:48 **** c3    1.9 http[ 9] |Connection: keep-alive
15:11:48 **** c3    1.9 body|2
15:11:48 **** c3    1.9 bodylen = 1
15:11:48 **   c3    1.9 === expect resp.status == 200
15:11:48 **** c3    1.9 EXPECT resp.status (200) == "200" match
15:11:48 **   c3    1.9 === expect resp.body == "2"
15:11:48 **** c3    1.9 EXPECT resp.body (2) == "2" match
15:11:48 **   c3    1.9 === expect resp.http.X-grace == "60.000"
15:11:48 ---- c3    1.9 EXPECT resp.http.X-grace (<undef>) == "60.000" failed
```

**Comment by nigoroll** [comment]
discussed on irc @hermunn asked me to see if this goes away with relaxed delays.
best options appears to try to stabilize this using barriers.
@hermunn can't reproduce.

**Comment by nigoroll** [comment]
cf04d394e5cb122b01135cd98532c0335a6fa60f improves for less drastic make -j, so this looks like the right place to look further

**Comment by hermunn** [comment]
> 15:11:48 ---- c3    1.9 EXPECT resp.http.X-grace (<undef>) == "60.000" failed

As far as I can see it, getting `<undef>` in `resp.http.X-grace` can only happen if this trip through VCL did not make it to `vcl_hit`.

Since the body `"2"` matches, this can only mean that it is in fact `c3` that starts the fetch that was supposed to be started as a background fetch from `c2`.

Can you confirm that this is happening on the failures, @nigoroll ? The point is that the `c3` client should go to the waiting list while the slow *background* fetch is happening, and then get to `vcl_hit` after that, when it is taken off the waiting list.

The solution, I think, is to change `-start` to `-run` for `c2` and convince ourselves that we are testing the same functionality. I will open a PR.
