### ISSUE TITLE
2019-03 release wishlist

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2762]
Require Python3

**Comment by slimhazard** [comment]
VMOD-modifiable and -implementable VDP filter lists, as we're getting for VFP in 2018-09.

Be able to say "run this ESI VDP instead of the standard ESI VDP". Should probably generalize that for the other standard VDPs such as ranges.

**Comment by fgsch** [comment]
> +       AM_PATH_PYTHON([3.0], [], [

Please don't use such an old version. We should aim for 3.4 or newer.

**Comment by slimhazard** [comment]
A new SLT tag ``SessError`` for session accept failures. The 2018-09 release adds diagnostics for accept failures, which is a Very Good Thing. Currently they're logged with ``Debug``, but ``Debug`` is used for a very wide variety of things, much of which is really only useful for Varnish devs trying to debug something.

``SessError`` would become a parallel to ``FetchError``. IMO it would be good UI to be able to look for it specifically, by eyeballing ``varnishlog -g raw`` or running ``varnishlog -g raw -i SessError``.

**Comment by slimhazard** [comment]
The ``vmod.tell`` addition to the CLI discussed in varnish-dev on May 18, 2018.

**Comment by slimhazard** [comment]
There was talk on ``#hacking`` earlier this year about something like ``for x, y, z ... do`` for vtc, with the goal of reducing the number of self-tests. Since we're now well over 700 tests, IMO we should look into that.

A number of tests do essentially the same thing as some other test, with one changed parameter, the idea being "verify that changing this variable does not have changed effects that it shouldn't have". Many of these were added for UDS -- a series of tests for UDS do the same thing that is done in other tests for TCP connections, to verify that essential functions don't work differently for the two kinds of sockets.

Putting no thought at all into the actual syntax, the idea would be something like:
```
for tcp, uds do {
        # ... tests that must work the same way for TCP and UDS sockets ...
}
```
I suspect that there's more than just the TCP/UDS cases that can be consolidated this way.

**Comment by Dridi** [comment]
Leaving the code duplication aspect aside, I'd rather keep tests split for better parallelism. I usually run 32 tests in parallel and even on a laptop from 2011 (that was not high-end then but above average) it doesn't slow down my system or prevents me from doing something else while the test suite is running. I have this *other* project with more than 1000 VTCs, same difference.

When a long-running test fails or even worse, times out, then I go from 1m30 (2018 laptop stat here) to usually one more minute. I'm not too keen on having more long-running tests.

**Comment by nigoroll** [comment]
I think @slimhazard has a point here and I do not quire share @Dridi s worries : While we certainly want to have a high degree of parallelism and do want to keep the total runtime of tests low, I think we could very well boil the number of tests down by an order of magnitude without negative impact on the total runtime.
That said, I think the highest potential regarding overhead reduction comes from avoiding varnishd instances. So I think we should focus first on what is required for consolidating related tests which could use a single varnishd.

Also, we could code parallelism into the iterators.

Regarding the for loop, I would be intersted in some actual dummy VTC code, I do not quite see how this would look for some real world examples

**Comment by Dridi** [comment]
> Also, we could code parallelism into the iterators.

I thought about that before replying, and I'm worried about how readable the log would then be.

**Comment by nigoroll** [comment]
@Dridi log the test variants into separate files? Anyway, detail alert...

**Comment by slimhazard** [comment]
More JSON support in the CLI. I would suggest ``-j`` for all informational responses:
* ``ban.list``
* ``panic.show``
* ``param.show`` (both the global list and individual stats)
* ``status``
* ``storage.list``
* ``vcl.list``

To mention: one of the clumsiest things I've tried to do is automate the interpretation of ``param.show`` output to get the flag status "experimental", "delayed", "restart" etc., because we just get the "free text" output from the CLI. That would be greatly simplified if a corresponding JSON just has a set of fixed values for the flag (strings or ints that act as enumeration values).

**Comment by rezan** [comment]
Are request scoped VCL objects still a candidate? I know previous discussions on this digressed into garbage collection and ref counting. I still feel this is all possible with basic request scope construction and destruction and immutable references. Anyway, I am down for another discussion on this if there is actual interest in attempting to get this feature into a release.

**Comment by bsdphk** [comment]
Bugwash:

Py3 mandatory. (Dridi or phk does it)

See fgs about py>3.4 above.

**Comment by Dridi** [comment]
Done in c22d8f777, 4fb3afa17, 089c2766c and bc37ac28b.

Anyone involved should look closely at bc37ac28b before we cut the release.
