### ISSUE TITLE
req_bodybytes regression

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2885]
https://github.com/varnishcache/varnish-cache/commit/9d3f1941a5ebcec36b022c46d4a0b356913c305c removed `req_bodybytes` from `struct req`, so now there is absolutely no way to access the cached request body length from vmods any more. See for instance https://github.com/varnish/varnish-modules/blob/master/src/vmod_bodyaccess.c#L205
There is also no way to access it from VCL because `std.cache_req_body`, which has the value from `VRB_Cache`, discards it to return BOOL.

Sensible Options IMHO:
* simply bring back `req_bodybytes`
* change `std.cache_req_body` to return the number of bytes

**Comment by bsdphk** [comment]
Not true:

     AZ(ObjGetU64(req->wrk, req->body_oc, OA_LEN, &u));

**Comment by Dridi** [comment]
Reopening for a short question: is this considered a VRT ABI breakage? I would say yes since it happened in `cache.h` but nothing was recorded in `vrt.h`, so maybe not? I'm asking for 6.0 back-ports so if `vmod-bodyaccess` needs an `$ABI strict` stanza I will happily both back-port the change and update the module accordingly.

**Comment by nigoroll** [comment]
> Not true:
> 
> ```
>  AZ(ObjGetU64(req->wrk, req->body_oc, OA_LEN, &u));
> ```

Thank you!

Ref: https://github.com/nigoroll/varnish-modules/commit/bbe82bdf27e741385254e270f3efc260f964916d

Leaving the ticket with @Dridi - Issue is solved for me.

**Comment by Dridi** [comment]
@nigoroll don't assign this to me, my question was to @bsdphk.

**Comment by Dridi** [comment]
Thanks for confirming!
