### ISSUE TITLE
VGC and VMOD entrypoints.

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2902]
This ticket replaces #2897 and #2898 

I have surveyed all the ways we call into VGC and VMOD code, and it is not very … consistent.

We have calls in a CLI context, which are allowed to fail, and expected to fail if something is not right, most notably VCL_EVENT_LOAD.

Here a ctx->msg is provided for communicating an error message back to the CLI.

We have calls in a CLI(-like) context which are not allowed to fail. VCL_EVENT_DISCARD, _COLD, _WARM, and no ctx->msg is provided, because failure is not an option.

(There are further nuances, VCL_EVENT_LOAD and _DISCARD sets ctx->method to VCL_RET_INIT and _FINI respectively, because VCL code is called, the other events _COLD & _WARM leave method at zero.)

We also have calls in CLI context to simply gather information, currently VDI->list(), which are not allowed to fail and where ctx->msg is the output buffer.

In none of these CLI(-like) contexts does PRIV_TASK make any sense, and there is never a ctx->vsl.

Then we have all the traffic-entries to execute compiled VCL code, which is where PRIV_TASK makes sense, ctx->msg does not, and ctx->vsl is always present.

I will 100% admit that it can be convenient for VMOD code to not have to bother about which kind of context it is operating in, and just grap PRIV_TASK or VRT_fail() and expect The Right Thing to happen, but I think it is the wrong way to go, because it adds code and overhead for very little saving.

I think my proposal going forward is:

In CLI(-like) contexts, there will always be a ctx->msg, and unless ctx->handling is VCL_RET_OK on return, ctx->msg contains a diagnostic.

This makes it possible to call VRT_fail() in all VGC and VMOD code.

The code calling into VGC/VMOD code may still be intolerant of failure, in which case it should report ctx->msg and panic - as we do today.

Information gathering code (like VDI->list()) can either panic on failure or substitute a "canned" response instead of ctx->msg, as makes most sense.

If a canned response is used, ctx->msg should be emitted somewhere (probably VSL(SLT_Error) ?)

cli_priv_task will be removed, and VGC/VMOD code is responsible for testing ctx->vsl before using VMOD_PRIV related functionality.

**Comment by nigoroll** [comment]
> In none of these CLI(-like) contexts does PRIV_TASK make any sense"

* it definitely makes a lot of sense for vcl_init and vcl_fini
* regarding the other cases, probably not, but we could provide it for consistency (still the same point I tried to make in #2897 )

So _cli_priv_task will be removed_ is a bad idea, but the rest regarding handling, msg etc. sounds reasonable to me.

**Comment by bsdphk** [comment]
I can probably be convinced to retain cli_priv_task for vcl_init/vcl_fini, but it will require a good convincing example of their utility.

**Comment by nigoroll** [comment]
discussed on IRC; summary FTR:
* one example of many: https://github.com/varnishcache/varnish-cache/blob/master/lib/libvmod_directors/vmod.vcc#L360
  * because shard reconfig is expensive, we keep a todo list as a priv_task on which we note all the changes, then apply them in one go when https://github.com/varnishcache/varnish-cache/blob/master/lib/libvmod_directors/vmod.vcc#L395 is called
* on the broader perspective, generic vmods (take variables as a simple example) should work in init/fini as in any other sub

We agreed that `PRIV_TASK` will stay for init/fini but we will not have it for any place else called from the cli.

VMODs should check `ctx->vsl`

**Comment by bsdphk** [comment]
Bugwash consensus:  Yeah, something like that.

**Comment by bsdphk** [comment]
We need to make this ticket actionable with a concrete list of changes necessary or we need to close it.

**Comment by nigoroll** [comment]
I want to re-check the initial note and comment on the state of the individual points

**Comment by bsdphk** [comment]
If 2020-3½ becomes 7.0, this becomes high priority

**Comment by nigoroll** [comment]
up-to-date review of @bsdphk's [proposal](https://github.com/varnishcache/varnish-cache/issues/2902#issue-409668644)

> In CLI(-like) contexts, there will always be a `ctx->msg`, and unless `ctx->handling` is `VCL_RET_OK` on return, `ctx->msg` contains a diagnostic.

We added `ctx->vsl` in 8e7b0f01d7c2bb0ae57c016f8bfb01d1fbd00dcb / #2997: When we do not have a `ctx->msg`, we have a `ctx->vsl`.

`ctx->msg` gets created by a _true_ argument to `VCL_Get_CliCtx()`, but we had a bit of a mess because where we init the `ctx` was inconsistent with the event:
* `ctx->msg` is present for `vcl.load` (through `vcl_cli_load()`) and `warm`/`cold` events (through `vcl_cli_state()`->`vcl_set_state()`).
  * but for a `cold` event throuch `VCL_Poll()`->`vcl_set_state()`, the `ctx->msg` was missing
* `ctx->msg` is `NULL` for `vcl.discard`
  * but for a discard from `vcl_cancel_load()` it is was present because the code reused the ctx from `vcl_load()`

I have fixed these points, but we should
* make up our mind about when we do want a `msg`: If a `cold` event cant fail, it would probably be better to not have the `msg` to begin with.
* reorder the code and in particular clean up the scope of the ctx

> The code calling into VGC/VMOD code may still be intolerant of failure, in which case it should report `ctx->msg` and panic - as we do today.

no action point here, IMHO

> Information gathering code (like `VDI->list()`) can either panic on failure or substitute a "canned" response instead of `ctx->msg`, as makes most sense.

The `ctx` for `backend.list` does not have a `msg` today and I think that such queries should not have the option to fail the entire transaction for user/state error.

> If a canned response is used, `ctx->msg` should be emitted somewhere (probably `VSL(SLT_Error)` ?)

This does not make much sense any more now that we have a `vsl` where we do not have an `msg` and I think it's better this way.

> `cli_priv_task` will be removed, and VGC/VMOD code is responsible for testing `ctx->vsl` before using `VMOD_PRIV` related functionality.

clearly no, as discussed before. `VMOD_PRIV` should stay as-is.

With respect to the release, I am not sure if we got any relevant impact. The fact that the presence (or not) of `msg` was, to some extend, arbitrary implies that existing code could not make safe assumptions about it. So unless I am overlooking anything, I would argue that fixing `msg` should be low risk and not relevant for release numbering.

@bsdphk I guess you will be the person most involved with the question about `cold` events: Should they have a `msg` or not? My opinion would be not.
After clarification, we can adjust the code appropriately and I would like to clean up the scope of the cli `vrt_ctx`.

**Comment by nigoroll** [comment]
@Dridi @bsdphk any myself agreed that we should not have an `msg` for `cold` events.

> phk: warm is a request, it can fail ("no contact to database" or whatever)
> phk: cold is an order, ("failure is not an option")
> phk: We will however allow cold to complain, and we will log the complaint.
> phk: but it was still an order.

I will fix the implementation based on this.

All other items from this ticket are resolved or obe.
