### ISSUE TITLE
H2 Incorrect RespProtocol in VSL

### ISSUE THREAD

**Issue by steven-j-wojcik** [varnishcache/varnish-cache#2905]
When using H2, the advertised RespProtocol in the VSL is `HTTP/1.1`. Though on the request side, it is returned as an H2 request. It appears to only be an issue with the VSL not the request itself.

## Expected Behavior
A RespProtocol of  `HTTP/2.0` in the VSL for H2 requests.

## Current Behavior
The RespProtocol in the VSL is shown as `HTTP/1.1` for H2 requests.

Output from curl with the same VCL showing the request was returned as H2:

```
X@X:/opt/varnish/vc$ curl localhost:8080 -vs --http2-prior-knowledge -o /dev/null
* Rebuilt URL to: localhost:8080/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x2073cf0)
> GET / HTTP/2
> Host: localhost:8080
> User-Agent: curl/7.61.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< date: Thu, 14 Feb 2019 16:33:11 GMT
< server: Varnish
< x-varnish: 4
< content-type: text/html; charset=utf-8
< retry-after: 5
< content-length: 224
< accept-ranges: bytes
< 
{ [224 bytes data]
* Connection #0 to host localhost left intact
```

## Possible Solution
I looked through the H2 code a bit and tried adding the RespProtocol but was unsuccessful.

## Steps to Reproduce (for bugs)
Run the below VTC.

```VCL
varnishtest "H2 RespProtocol"

server s1 { } -start

varnish v1 -arg "-p feature=+http2" -vcl+backend { 
	sub vcl_recv {
		return (synth(200));
	}
} -start

logexpect l1 -v v1 {
	expect * *		RespProtocol		HTTP/2.0
} -start

client c1 {
	stream 1 {
		txreq
		rxresp
	} -run
} -run

logexpect l1 -wait
```

## Your Environment
* Version used: master
* Operating System and version: Ubuntu 16.04
* Source of binary packages used (if any): NA

**Comment by bsdphk** [comment]
Oh boy...

When I started Varnish in 2006, I made the protocol a property of the request and response, based on available evidence at the time.  Subsequent developments have gone in an entirely different direction, and I think today the correct view is that the protocol is a property of the client or backend we are communicating with.

With that in mind, I am tempted to:

A) remove HTTP_HDR_PROTO

B)  Move X.http.proto to X.proto in VCL

C) Only VSL the protocol in {client|backend}_gethdrs and client_response

I write "tempted to" because this is a pretty invasive change for very little concrete benefit, at best we save some VSL records and gain some consistency.

On the other hand, if not now, when ?

**Comment by Dridi** [comment]
> B) Move X.http.proto to X.proto in VCL

We already have `{req,resp,obj,bereq,beresp}.proto` in VCL, those aren't header fields per se (not even pseudo headers in h2).

**Comment by bsdphk** [comment]
Yeah, step B was unclear:   req.proto -> client.proto etc.

**Comment by bsdphk** [comment]
Bugwash:

Not worth it.

Have H2 spit out a VSL RespProto record to set the record straight
