### ISSUE TITLE
bundled / supported vmods review

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2912]
motivated by expressions of frustration in https://github.com/varnishcache/pkg-varnish-cache/issues/95

* VS maintains varnish-modules, but only for latest LTS releases. There is https://github.com/varnish/varnish-modules/pull/119 and https://github.com/nigoroll/varnish-modules which I try to keep up-to-date with current master
  * @ingvarha mentioned recently on IRC that he is now building this branch for fedora
* We (UPLEX) maintain a bunch of additional vmods which I would consider worthy of consideration for wider deployments. Just to name those which I believe could be most useful:
  * https://code.uplex.de/uplex-varnish/varnish-objvar
  * https://code.uplex.de/uplex-varnish/libvmod-blobdigest
  * https://code.uplex.de/uplex-varnish/libvmod-re2
  * https://code.uplex.de/uplex-varnish/libvmod-re

Question:
* Do we want to bundle additional vmods in https://github.com/varnishcache/varnish-cache
* Could varnish-modules maybe become a project under https://github.com/varnishcache ?
* If yes, we could add move vmods there (which?)
* Should we resume building varnish-modules (and others?) from https://github.com/varnishcache/pkg-varnish-cache

**Comment by lkarsten** [comment]
Hi.

Thanks for responding to my "complaint" in pkg-varnish-cache.

I'm not sure that "maintained" is the correct word. My regexp patch to vmod-cookie has been there for a 3-4 months now, with not as much as an acknowledgement. There is community interest, but no interest in adding it. It may be the code quality, but I wouldn't know.

The main issue before has been what vmods to add to core, and who will maintain them.

I understand that pulling in build and run time dependencies to core is a tough sell (as it should be), but the ones I most often need are standalone. vmod-header and vmod-cookie come to mind as things that should have been in core a long time ago. These are also close to feature complete, and looking at the commits the the couple of years, most of the changes are for autotools or documentation.

When it comes to vmods that pull in exotic runtime libraries, I don't have much to add. I don't see any easy/good solutions there except for standalone vmod packages (per "vendor") as we have now.

**Comment by bsdphk** [comment]
I'm going to abstain on this one.

**Comment by slimhazard** [comment]
For discussion I'd like to propose some criteria for taking up a VMOD in the Varnish distribution:

* The VMOD is known to be in widespread use and in high demand for common use cases.
* Or, if the VMOD is relatively new, it provides compelling features that the dev group agrees will be a valuable enhancement for the project.
* The VMOD does not create dependencies on additional external libraries. VMODs that are "glue" for a library remain third-party, so that we don't force Varnish deployments to install more than admins choose to install.
* The code follows project conventions (passes make distcheck, follows source code style etc). At least we should demonstrate that it can be adapted for that, say by fixing it up in a PR.
* The Varnish dev group commits to maintaining the code for the long run (meaning that there is a consensus that we're comfortable with the code).

IMO a few things follow from that:

* Widespread use and high demand: VMOD header from varnish-modules comes to mind. IMO vsthrottle has a good record as a solution for rate-limiting.
* VMOD re2 doesn't pass the test, because it depends on another library (libre2 for regexen).
* [VMOD selector](https://code.uplex.de/uplex-varnish/libvmod-selector), on the other hand, doesn't have external dependencies, and IMO has the best features of re2 (it does the matching against fixed strings, not patterns). But I have no idea if there is any demand for it outside of UPLEX projects (and mine is not an unbiased opinion, for obvious reasons).
* VMOD blobdigest actually also has a library dependency, in this case in the form of public domain code (librhash) that is included in the source. That doesn't force an additional installation, but in practice it has meant that the foreign code hasn't been updated in quite a while. The foreign code doesn't follow project conventions (it won't build with clang), and I'd be surprised if the Varnish group would be willing to take it up in the Varnish source.

Overall I think it would be great relief if varnish-modules were available in packages. As much as I think that building and installing software should be a minimal skill requirement, the reality is that most people just want to say apt-get and I'm done.

**Comment by bsdphk** [comment]
Bugwash;

Good criteria.

Also need criteria for maturity/stability.

Should go in devguide.

**Comment by nigoroll** [comment]
butwash 2:
decide on vmods based on PRs.
