### ISSUE TITLE
suspected objcore leak regression since Feb 7

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2945]
Documenting to be able to reference the issue:

![objcore png](https://user-images.githubusercontent.com/1528104/54361070-872d1d00-4666-11e9-831e-d62ca79ae318.png)

Since taking d0b398738eb615969ae4f92095b130949b0006d7 + unmerged PRs from https://github.com/nigoroll/varnish-cache/tree/unmerged_code into production, apparently there is a clear increase in the objcore/objhead ratio.

Previous version was 69574c5aff714d34904837a5eae188797ff78961 + unmerged PRs from https://github.com/nigoroll/varnish-cache/tree/unmerged_code 

The only vcl difference taken into production shortly before binary deployment was replacing a `return(miss)` in `vcl_hit{}` with `return(restart)`

**Comment by slimhazard** [comment]
Assuming that Feb 7 refers to 2019, we have the interesting situation that there are no commits with that date. Of course that's not the same as the day when a commit is pushed.

Just spitballing here, since hit & miss appears to be involved -- could this be related in any way to the accumulation of hitmiss objects that we had some time ago? IIRC there was a fix for that, but it doesn't seem out of the question that this change -- removing ``return(miss)`` and restarting with ``always_miss`` -- may be a situation that hasn't been tested much.

**Comment by nigoroll** [comment]
@slimhazard I did give the exact commit id.
In fact this smells like a user error (= my mistake) because of the fact that the old #1799 workaround did not always need to restart and run into `hash_always_miss`, the vcl code I got as-is now does.
Final conclusion pending, I am testing.

**Comment by nigoroll** [comment]
Confirmed: the issue was caused by `hash_always_miss` being hit for many more cases.
My diagnosis was confused by #2946 which is real but unrelated.
