### ISSUE TITLE
WS_Reserve() return inconsistent

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2967]
Ref: https://github.com/varnishcache/varnish-cache/blob/f106ed834f31f2ab5c798c56a6ca48225615dc45/bin/varnishd/cache/cache_ws.c#L242

* case a: If `WS_Reserve()` is called with `bytes > 0` and the reservation cannot be fulfilled, we return 0 with `ws->r == NULL`.
* case b: if `WS_Reserve()` is called with `bytes == 0` and there are 0 bytes available, we also return 0, yet with `ws->r == ws->e`.

`WS_Release()` asserts `ws->r != NULL` (same for `WS_ReleaseP()`)
https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishd/cache/cache_ws.c#L270
so error handling should only call `WS_Release()` for case b

In varnish-cache core, there are only a few cases where we call `WS_Reserve()` with `bytes > 0` and they either get it right or assert (e.g. for the session where I think it is reasonable to assert that the session workspace is large enough), so there is no real issue here. Yet still I think we should make this consistent.

I think the most POLA way would be to always leave with `ws->r != NULL` such that calling `WS_Release()` is always the right error handling.

**Comment by slimhazard** [comment]
To put this another way (since it was my bug in a VMOD that got caught): I thought it was an error to call ``WS_Release()`` after ``WS_Reserve()==0``, because in the overflow case, ``ws->r==NULL``, and ``WS_Release()`` would fail the assertion.

But in fact, ``WS_Reserve(ws, 0)==0`` can *only* happen if the workspace is right at the limit: ``ws->f==ws->e``. The 0 return is not because of overflow, but because ``ws->r`` gets set, and ``pdiff(ws->f, ws->r)==0``. Then you *have to* call ``WS_Release()`` to reset ``ws->r==NULL``.

So you better know that: ``WS_Release()`` MUST NOT be called after ``WS_Reserve(ws, bytes)`` if ``bytes != 0``, but MUST be called if ``bytes == 0``. I got POLA'd.

**Comment by Dridi** [comment]
I don't think `ws->f==ws->e` is the only case where this may happen because of memory alignment, but close enough.

At the same time I don't consider this inconsistent since the purpose of reserving memory is to use what's available and in the case of a zero-length reservation it doesn't trigger my POLA as I consider it fail-safe (unless there was already an ongoing reservation).

I would rather go for a docfix here, although I don't remember seeing any formal docs around `WS_*`.

**Comment by nigoroll** [comment]
@Dridi I might not have made this clear enough: The point here is that for proper error handling, the calling code needs to be different depending on the `bytes` parameter:

```
u = WS_Reserve(ws, 0);
if (u == 0 || u < min) { /* u == 0 for clarity, is implied */
    WS_Release(ws, 0);
    return (...);
}
```

vs.

```
assert (b > 0);
u = WS_Reserve(ws, b);
if (u == 0)
    return (...);
```

I think it would be more straight forward and avoid unnecessary caller errors if the right pattern would be the first also for `b > 0`

**Comment by bsdphk** [comment]
Consensus:  This is confusing.

Add new WS_ReserveAll(ws) which always requires WS_Release() to be called.

Down the road, disallow bytes=0 to WS_Reserve()
