### ISSUE TITLE
Interactive varnishstat -f confusion

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2990]
On multiple occasions I was told that people get confused when they limit the counters to a given list and yet only a subset shows up.

In general it is well understood that counters with the value zero don't show up, almost all of the time they don't realize that we have different kinds of counters and some may only show up only if we increase the verbosity with the `v` key.

There are a couple things I would like to consider:

- Start right away with verbosest verbosity when `-f` is used
- Exclude verbosity levels not covered by `-f` when rotating verbosity with `v`
- Consider an extra verbosity level to show all counters, even the zeroes

The second point may be to complicated to implement with dynamic VSCs if we use glob matching, and possibly not worth it.

**Comment by nigoroll** [comment]
The second point may be too complicated to understand for someone with limited capacity like me ;)

+1 on the first

on the third point: we got `<d>`, should we maybe have a command like option as well?

**Comment by bsdphk** [comment]
No opinion.

**Comment by Dridi** [comment]
@nigoroll let's imagine that your `-f` selection leads to the following verbosity levels:

- normal: 3 counters
- diag: no counter
- debug: 1 counter

Cycling through with `<v>` or `<V>` could skip the diagnostic level, hence dynamic VSCs may render this too complicated and not worth it.

TIL about `<d>` so forget about the third point, I RTFM in general but forgot about that one (and others actually).

**Comment by Dridi** [comment]
And f41055d326fdfabd75a1afd0653ea9357a13d25e is evidence that I rarely use `varnishstat` in interactive mode.

**Comment by bsdphk** [comment]
Dridi tries to improve UX based on bugwash discussion.

**Comment by nigoroll** [comment]
bugwash notes:
* add <h> for curses help
* set <v> by default to include all -f matches
* make <v> setting more prominent in interface, e.g.
* `press h for help` or toggle counters with the help docs?
* @Dridi wants to find someone to attempt a PR

**Comment by Dridi** [comment]
Update: a while ago I pushed some ground work that would allow the key bindings reference to be shared by the event loop, man page and help screen. The help screen will follow at some point.

**Comment by kn-cpt** [comment]
> set `<v>` by default to include all -f matches

This would fix `varnishstat -f '*overload*'` in that it actually shows the requested value without pressing `v`, just like the same invocation with an `-1` added shows it.

Above mentioned PR came out of this very confusion.
I think the user interface should show exactly what the user requested, hence to include all `-f` matches by default seems to be the right approach.

I'd also argue that this implies showing matches even when their counters are all zero;
otherwise there is no way to distinguish (in curses mode) between a mismatching pattern/no results and intentionally hidden results.

To clarify: considering `varnishstat -f '*overload*'` to monitor sessions exiting with `OVERLOAD` error for example, not showing anything until counters grow is neither intuitive nor helpful.

Showing matching counters at zero is confirmation to the user that the values of interest  do not change.

**Comment by Dridi** [comment]
I would argue that once we have a help screen counters with a zero value should be less of a problem.
