### ISSUE TITLE
Add Varnish native support for FCGI (FastCGI) protocol (php-fpm)

### ISSUE THREAD

**Issue by glensc** [varnishcache/varnish-cache#3004]
If Varnish could support FCGI backends directly, this would make certain<sup>1</sup> setups radically simpler and fault-proof, without having to have fcgi->http translation (nginx, lighttpd).

<sup>1</sup>: serving static content from backend over fcgi is not recommended.

----

As I could not find any existing issue in this repo I thought to create one for tracking. Even if this doesn't get implemented there would be a place to find reasoning why not.

For example [https](https://varnish-cache.org/docs/trunk/phk/ssl.html), [h2](https://info.varnish-software.com/blog/topic/http2) and [PROXY protocol](https://github.com/varnishcache/varnish-cache/issues/943).

**Comment by glensc** [comment]
found older ticket (FastCGI, not FCGI keyword):
- https://github.com/varnishcache/varnish-cache/issues/1019

**Comment by Dridi** [comment]
The github issue tracker is for bugs only as stated in the issue template.

For feature requests or general questions we use other support channels:

https://varnish-cache.org/support/#mailing-lists

In this particular case, since backends (aka directors) can be implemented via modules, someone should write such a module or sponsor the development of such a feature. Only then could it be considered for inclusion in this repository.

**Comment by glensc** [comment]
thanks for the quick answer, but mailing lists are so 90s, not going to register to a mailing list to submit one email that is getting the same answer: no ;)

**Comment by neeleshramputh** [comment]
> thanks for the quick answer, but mailing lists are so 90s, not going to register to a mailing list to submit one email that is getting the same answer: no ;)

Kindly sponsor this development
