### ISSUE TITLE
Filter the log query based on VCL_call

### ISSUE THREAD

**Issue by EricBatty** [varnishcache/varnish-cache#3015]
hi，
I used the following command to query the filtered varnish log for the correct information returned to me.
```
[root@node122 ~]# varnishlog  -g request -d  -q ' RespStatus >= 500 and RespStatus < 600'
[root@node122 ~]# varnishlog  -g request -d  -q 'RespStatus == 200' 
```
But when I use 
```
varnishlog-q 'VCL_call ~MISS' 
```
to filter the query. It returned a different result than I expected. I just want the missing information from VCL_call, but it returns all the information included:
```
...
--  VCL_call       BACKEND_FETCH
...
...
-   VCL_call       RECV
...

```
It wasn't just "VCL_call MISS," which confused me. What can I do to get him to return only "VCL_call MISS"? I just want to filter the missing log information from the query.

The operating system version I am using is CentOS7.6 varnish version. This is 4.0.5.

**Comment by gquintard** [comment]
Hi,

We only use github issues for bugs and not general support. Please use one of the other channels: https://varnish-cache.org/support/.

Note, I believe what you want is `-I VCL_call:MISS` even though it doesn't really make sense since the result doesn't really yield useful information.

Regards,
