### ISSUE TITLE
Modifying vcl_hash causes tests to timeout

### ISSUE THREAD

**Issue by jloh** [varnishcache/varnish-cache#3063]
## Expected Behavior

Bcakend requests don't time out

## Current Behavior

Backend requests timeout and fail

## Steps to Reproduce (for bugs)
1. Create a test that adds to `vcl_hash` via `hash_data`
2. Run test
3. See backend requests fail

Example tests and logs here https://gist.github.com/jloh/a56b705dedd66f9f8c325e75d38c7898

## Context

Trying to write some unit tests using `varnishtest` to cover some additions to `vcl_hash` however whenever testing them backend requests just timeout and fail. Note I'm not completely overriding `vcl_hash`, just adding via `hash_data` if a header is present.

## Your Environment

* Version used: varnish-6.2.1 revision 9f8588e4ab785244e06c3446fe09bf9db5dd8753
* Operating System and version: OSX Mojave (10.14.6)
* Source of binary packages used (if any): built/installed from homebrew

**Comment by gquintard** [comment]
this is normal behavior: the second request doesn't have the same hash as the first one, so it's a new object and varnish tries to go to the backend, but you didn't tell `s1` to serve another file, so you get a timeout.

If you want the backend request to fail faster, add a `close` at the end of `s1`'s scenario:

```
server s1 {
  rxreq
  txresp
  close
} -start
```

**Comment by ErisDS** [comment]
Thanks for replying so quickly. I worked with @jloh to try to figure this out before posting an issue and we would _never_ have figured that out without your help. Not in a million years.

varnishtest is an insanely powerful & useful tool and I don't want to diminish the work of an OSS project cos I know how that goes, but I am wondering if we are missing something...

The docs mention this which is an alpha made 5 years ago and not maintained: https://github.com/xcir/vtctrans

Is there some other trick or tool folks use to run varnishtest and get some form of output mere mortals can cope with?

**Comment by gquintard** [comment]
Hi,

Note that I replied because this one was a quick fix, but we try to keep the bugtracker for bugs. For the rest, please use the other support channels: https://varnish-cache.org/support/

`varnishtest` can be a bit finicky, and we have a man page for its syntax (`man vtc`), that should help a bit. If you feel that information is missing, please submit a pull request and I'll gladly look at it (most of the docs is extracted from the source code, ask for pointers if something isn't immediately clear).

The `varnishtest` output has changed a bit, so I'm not sure it still applies, but if anything, the output should now be easier to parse. Propositions are always welcome, but I think building a small prototype in go/python first to demonstrate where you want to go would be useful
