### ISSUE TITLE
Type specific methods, where do we go ?

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#3112]
This is a discussion ticket for todays bugwash.

Now that we have type specific methods, where do we take them ?

    some.expression.yielding.backend.resolve() ?

    something.http.cache-control.collect() ?

Do we think that would be an improvement on VCL syntax ?

Please note: This discussion is 100% and only about VCL syntax, not the precise implementation or semantics of the examples proffered.

**Comment by Dridi** [comment]
Related to #3103.

**Comment by Dridi** [comment]
A bit of context, true as of today:

- some types now have `.properties` or `.methods()`
- expressions can be simple like `beresp.storage.free_space`
- they can be complex like `(req.http.host + req.url).lower()`
- there's no technical limit to dot-chaining method calls
  - example: (STRING expr).lower().upper().lower().upper()...

Bugwash summary:

I'm only reporting what I believe was the final consensus on various topics, I took the liberty of adding a couple more suggestions that didn't come up during the bugwash.

- nobody against adding more methods to types
  - general consensus is yes, that would be an improvement
- methods with arguments would definitely be more useful
- we didn't discuss type methods returning VOID
  - in other words, statements: `(expr).method(...);`
  - example: `something.http.cache-control.collect();`
- no clear consensus on vmods having the ability to add type methods
  - @bsdphk suggested a syntax: `(DURATION expr).std.format("%.3f")`
  - I suggested that any function taking a TYPE as its first parameter could translate into a type method
  - for phk's example in vmod_std `$Function STRING format(DURATION, STRING)` would be enough to recycle a plain function into a type method
  - otherwise we might prefer a new dedicated stanza (for example `$TypeMethod`)
  - this syntax opens a can of namespace worms regardless of the VCC implementation
    - post-bugwash alternative proposal: `(DURATION expr).std::format("%.3f")`

To be revisited next week.

**Comment by nigoroll** [comment]
+1 for @Dridi s suggestion _that any function taking a TYPE as its first parameter could translate into a type method_
I am not quite up to speed with the type methods yet, but I still wonder if the dot is the best choice to make the syntax readable and unambiguous.
Why exactly did we decide for it and against, for example, the arrow `->`?
I would find
```resp.http.cache-control->std.collect()->myvmod.fixup_ttl()```
more readable than
```resp.http.cache-control.std.collect().myvmod.fixup_ttl()```

**Comment by nigoroll** [comment]
On the VOID return, I guess the logical thing would be that it breaks chaining.

**Comment by Dridi** [comment]
The problem with `->` is that the `-` part is valid in symbols, so this creates an ambiguity with the `gt` operator.

**Comment by nigoroll** [comment]
@Dridi isn't this just a parser deficiency to be solved? We said we wanted to talk about the syntax, and from that perspective, I think the dot is not ideal.

**Comment by Dridi** [comment]
Yes and no.

Technically, the dot syntax for `.properties` made things backwards compatible for cases like `beresp.storage.free_space` and then it grew the ability to expect brackets and be called a `.method()` instead.

So the dot syntax is already a thing, and I'm not too keen on breaking it already. I'm also not too keen on introducing C-like rules regarding ambiguous tokens (eg. `a = b+++c;`) in VCL.

**Comment by bsdphk** [comment]
The '.' vs '->' distinction were (almost) unnecessary i C to begin with.

I do not really see any added value in introducing it in VCL, unless it provides some tangible benefit, which I have a hard time seeing.

So for now, I'd prefer to align with python and use dots all the way.

**Comment by nigoroll** [comment]
dicussed between @bsdphk @Dridi and myself:
* the ticket was intended to bring the subject in front of the bugwash to introduce type-specific methods and to make people think.
* It has served that purpose well.
