### ISSUE TITLE
Inserting binary objects in vcl_backend_error

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#3114]
Issue: when synthing error responses in vcl_backend_error, there is no way to synth a binary body.

Expected: being able to insert a static "sorry, we have issues" jpeg into cache when we don't have a backend.

Some context: 
I have a rig which serves (many) live images from a single backend. It is very important that this returns something sensible, but never something stale, when the backend is down.

First attempt with `set beresp.body = std.fileread("error-500.jpeg")` returns the first 4 bytes of the JPEG, since the later bytes in the file includes a \0. No warnings of a partial file being returned anywhere I can find. VFIL_readfile() will read the whole file as I understand it, but std.fileread() only use up until the first \0.

Having discussed this a bit with Geoff and learning about uplex' vmod-file, I think a way forward would be to allow:
1) make a BLOB from the contents of a file on disk (with PRIV_VCL lifetime), and
2) assign this blob to beresp.body in vcl_backend_error somehow.

In VCL it could look like:
```
sub vcl_init {
   new errorblob = blob.read_file("/etc/varnish/error.jpg");
}

sub vcl_backend_error {
    if (bereq.backend == imageserver && bereq.url ~ "\*.jpg") {
        set beresp.content-type = "image/jpeg";
        set beresp.body = errorblob;
    }
}
```

Workaround: I'm experimenting with returning a base64-encoded `<img src="data:image/jpeg;, ">` page instead, but I'm not sure that will work everywhere.

**Comment by nigoroll** [comment]
I totally agree that is this missing (side note: I one wrote the trivial [vmod_blobsynth](https://code.uplex.de/uplex-varnish/libvmod-blobsynth) to do the same thing on the client side).
I _tend_ towards just making `.body` a `BLOB`. Yes, it will break VCL, but `synthetic()` could stay and converting text into blob is a no-brainer.

**Comment by bsdphk** [comment]
As long as we dont break existing VCL I'm fine with this.

**Comment by Dridi** [comment]
I was requested as a reviewer for #3100 and I had a first stab at this when it was first brought up on IRC. With both in mind I submitted #3116, on top of which I'm convinced I can make this work without much disruption.

If nobody minds, I'm assigning this to myself.

**Comment by bsdphk** [comment]
Right now we have an "ambient" rule that everything can be converted to STRING in VCL.

Right of the bat, I dont see why we could not augment that with a rule that STRING can be converted to BLOB.

Then we could simply make the type of (be)resp.body BLOB ?

The inherent madness in this idea is of course which characterset a STRING has...

**Comment by nigoroll** [comment]
I like @bsdphk s idea _a lot_. It would not just solve this case, but also simplify many others by removing pretty pointless blob.encode(encoded=STRING) calls.
What is the worry about charactersets? As long as we blob-wrap just the bytestream, which new issues do you see?

**Comment by bsdphk** [comment]
The worry about charsets is that we have never said what (charset-)encoding STRING has, because it is implicit in HTTP headers being ASCII.

For *.body encoding matters, and most people will want UTF-8 and some people will want something different (ISO8859-1 etc.).

*Ideally* we should do the py3 thing, where STRING is nominally unicode and you have to explicitly state the encoding when serializing a STRING.

But that would not only be overkill and selling out performance for no good reason, it would also be pointless in (1-epsilon) of all cases.

Still, I'm sure some users will get confused, but may we just need to explain that whatever charset they use for VCL is the charset the BLOB will use.

**Comment by nigoroll** [comment]
@bsdphk thank you for the explanation. I am with you except for one aspect: In my opinion, it is POLA to take whatever encoding is in the STRING and BLOB-wrap it as-is. While the unified encoding is a useful feature, I would rather think that it is actually harder to explain than just preserving whatever encoding was used in the fist place.

So: We agree that generically casting/folding STRING into BLOB is the best idea so far with respect to setting `(be)?req\.body`.

@Dridi do you agree? If yes, would you also look after this?

**Comment by nigoroll** [comment]
bugwash in favor:
* accept STRING values wherever BLOB is accepted
* the fold/cast is transitive, so all other types folding into STRING are also accepted

@Dridi please let us know if you would be so kind to look after this

**Comment by Dridi** [comment]
I already have some work in progress (see https://github.com/varnishcache/varnish-cache/pull/3116#issuecomment-551506892) in this area and I will happily throw some of it away to move in this direction.

In my work-in-progress branch I have 3 patches I would like to push regardless since they improve libvcc without changing any behavior. However those patches are built on top of #3116 that I would like to merge first and foremost. I have 2 other patches from my branch I'd like to keep, but they will not conflict so I'm not worried.

I think #3116 is ready to be merged in its current state, especially since it fixes a `(be)?resp\.body` bug in addition to expanding `+=` support (and generally simplifies the `set` action).

**Comment by Dridi** [comment]
Discussed with @nigoroll and @bsdphk:

- We want to treat BODY assignments differently, and it should be transitional
  - `set [be]resp.body [+]= STRING|BODY`
  - I will amend the pull request with the "alternate assignment table" from a previous patch
  - This pull request would no longer touch the builtin VCL
  - In the future BLOBs may optionally be linked
- We still want STRING to automatically cast to BODY (it consumes workspace)
- `std.blobread()` should really be `blob.fileread()`
  - move the underlying infrastructure to VFIL to avoid duplication
