### ISSUE TITLE
varnishncsa syslog mode? / -w required for -D and -P parameters?

### ISSUE THREAD

**Issue by ibantxo** [varnishcache/varnish-cache#3179]
I am launching the command from systemd Ubuntu server 18.04, without -w parameter, and with -D and with -P

##  Expected Behavior
Launching with no problem

## Current Behavior
There is an execution error: ~missing -w parameter

## Possible Solution
Get working without -w

## Steps to Reproduce (for bugs)
1. Change on systemd->varnishncsa deleting the default -w .log

## Context
I want to send all the output to syslog

## Your Environment
* Version used: 5.2.1
* Operating System and version: Ubuntu server 18.04
* Source of binary packages used (if any) default

**Comment by nigoroll** [comment]
To rephrase: Do we want to support writing to stdout in daemon mode?
I got no clear opinion.

**Comment by bsdphk** [comment]
"writing to stdout in daemon mode" makes no sense, in daemon mode stdout is /dev/null.

If we are talking about some other mode than daemon mode, then somebody needs to explain what that mode is, and what the process' circumstances are.

**Comment by nigoroll** [comment]
Yeah, it would be a not-quite-daemon mode where stdout was not closed.

**Comment by Dridi** [comment]
If the output needs to go to syslog then it must be run in the foreground:

```
varnishncsa | your-syslog-forwarder
```

If you are doing that via systemd then change your service type to simple, and remove all the `-D`, `-P` and `-w` options. I'm not closing on the ground that 5.2.1 is EOL, because the same will happen with 6.x releases but you should upgrade anyway.

Either way, if you do not wish to write to a file, you cannot use the daemon mode as explained above.

Please let us know more about your use case but I suspect this is only a matter of a setup mistake.

**Comment by ibantxo** [comment]
Hi! Many thanks for your all answers!!!

I have changed my /lib/systemd/system/varnishncsa.service file, and the logs are appearing inside rsyslog.  Many Thanks again!!!

```
[Unit]
Description=Varnish HTTP accelerator log daemon
Documentation=https://www.varnish-cache.org/docs/4.1/ man:varnishncsa
After=varnish.service

[Service]
#Type=forking
Type=simple
PIDFile=/run/varnishncsa/varnishncsa.pid
RuntimeDirectory=varnishncsa
User=varnishlog
Group=varnish
#ExecStart=/usr/bin/varnishncsa -a -w /var/log/varnish/varnishncsa.log -D -P /run/varnishncsa/varnishncsa.pid
ExecStart=/usr/bin/varnishncsa -a
ExecReload=/bin/kill -HUP $MAINPID
PrivateDevices=true
PrivateNetwork=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=full
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=varnishncsa

[Install]
WantedBy=multi-user.target
```

**Comment by Dridi** [comment]
Thank you for the clarification.

You shouldn't update the service file in `/lib` or `/usr/lib` otherwise it will be overwritten next time you update the package (reminder: you should NOT stay on any 5.x series). Please refer to the systemd documentation for that.

Alternatively you can have a look at this [tutorial](https://docs.varnish-software.com/tutorials/configuring-systemd-services/) to quickly learn more about systemd operations.

During today's bugwash we also considered a syslog mode for varnishncsa. We can either use this ticket to keep track of the feature, move it to a VIP core just close this issue. I have no opinion on that specific point.

**Comment by nigoroll** [comment]
maintainer pow-wow decision;
We do not see a point in adding a syslog mode because
* of separation of concerns (one tool, one purpose)
* there is a good solution, see above

hello to @slimhazard

**Comment by slimhazard** [comment]
Hello @nigoroll!

Other than getting us to wish one another a nice day, what is it that you wanted to say with the mention? Yes I've worked on various things that use the log API, but I'm not clear on what exactly the connection is.
