### ISSUE TITLE
Abnormal memory usage pic with Transient

### ISSUE THREAD

**Issue by anthosz** [varnishcache/varnish-cache#3234]
## Steps to Reproduce (for bugs)
1. Randomly

## Context
- Varnish works well during several days/hours (35GB in storage_0/ avg of 382 MB in transient storage).
- After ~2 days: we have this strange behavior:
![image](https://user-images.githubusercontent.com/14294064/75521432-05193e00-5a08-11ea-9176-8c037020e668.png)
```
panic.show:
Backtrace:
errno = 12 (Cannot allocate memory)
thread = (MPL_req0)
```
We can see a pic of usage of 15GB of transient. Do you know how to explain this behavior? Memory leak?

For a workaround, I also tried to move transient storage to FS: -s Transient=file,/varnish/transient,150G but all space was used after several hours:
![image](https://user-images.githubusercontent.com/14294064/75521815-c637b800-5a08-11ea-9422-b331b67ed470.png)

## Your Environment
* Version used: 6.3.2 compiled
* Operating System and version: RHEL 7

**Comment by nigoroll** [comment]
Transient is used for uncacheable (pass) objects. Best advise is probably to check for many and/or large pass objects.
From the graphs, I see absolutely no indication for a leak because transient usage goes down inbetween crashes.
Other than that, as long as there is no clear indication for a bug, please [resort to other support channels](http://varnish-cache.org/support/index.html)
