### ISSUE TITLE
need domain for dns tests / v00016.vtc fails on Linux/powerpc 

### ISSUE THREAD

**Issue by ingvarha** [varnishcache/varnish-cache#3237]
v00016.vtc fails on Linux/powerpc

Environment: Ubuntu 16.04 (Xenial), 32-bit powerpc

Logs attached

Ingvar

**Comment by ingvarha** [comment]
[varnish-cache-issue-3237.txt](https://github.com/varnishcache/varnish-cache/files/4271060/varnish-cache-issue-3237.txt)

**Comment by Dridi** [comment]
Can you try b0e6629ae87db8ce41df02b101ed4c9e66b75190?

**Comment by bsdphk** [comment]
We should get the dns-canary fixed, and use the hostname of that canary.

The dns-canary is the FQDN we look up to see if DNS works properly or if we are without connectivity or behind some captive portal to decide the "feature dns" directive.

It needs to be a dedicated FQDN used only for this, rather than the current "varnish.org", and it should respond with a non-routable, non-RFC1918 IP number.

**Comment by ingvarha** [comment]
Changing to fastly.com makes the test work on my old ppc xenial.

**Comment by nigoroll** [comment]
> We should get the dns-canary fixed, and use the hostname of that canary.

I can help out if you are ok with a different domain, but if you want it under varnish-cache.org, I guess this ticket will stick with you

**Comment by Dridi** [comment]
It turns out I had already back-ported the suggested patch as 93231dde2 in the 6.3 branch during my recent work on release notes.

**Comment by bsdphk** [comment]
I would prefer we have it under the varnish-cache.org so that it vtest does not break for totally unrelated decisions in a different organization.

**Comment by nigoroll** [comment]
@bsdphk agree. Who has got access to the DNS records?

**Comment by bsdphk** [comment]
Dridi sorts out after 6.4 release.
