### ISSUE TITLE
RFC: sub vcl_lookup

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#3259]
Today with VCL we have two subroutines where we can influence the cache lookup..

In `vcl_recv` we can generally set `req.*` variables such as `req.grace` or `req.hash_always_miss` to tweak cache lookups.

In `vcl_hash` we compute the hash, and jump straight to a lookup in core code.

We might need the hash to make meaningful lookup decisions though. With vmod_saintmode for example, we can turn a backend sick for a given hash, and it works in the context of a cluster-type directors that may pick a different backend.

It doesn't work for other purposes and the workflow I'm suggesting is the following:

```vcl
sub vcl_recv {
    set req.backend_hint = my_sm.backend();
}

sub vcl_lookup {
    if (std.healthy(req.backend_hint)) {
        set req.grace = 1m; /* lower maximum grace for healthy backends&objects */
    }
}
```

The `vcl_lookup` step would happen between `vcl_hash` and `vcl_{hit,miss,pass}`, only if `vcl_recv` returned with a `hash` transition, giving one last opportunity to influence the in-core lookup based on `req.*`, _\_including\__ `req.hash`.

Suggested transitions: `go_go_go`, `restart`, `fail`.

Suggested builtin:

```vcl
sub vcl_lookup {
    return (go_go_go);
}
```

**Comment by nigoroll** [comment]
@Dridi I see a case for this.
WRT the return value, I would suggest the simple `ok` as agreed for `vcl_backend_refresh` in #3102

**Comment by Dridi** [comment]
Yes, I was going for `ok` but typo'd `go` and now you spoiled all the fun.

**Comment by nigoroll** [comment]
we must not make any more jokes before the 1st of next month ;)

**Comment by bsdphk** [comment]
I raise a very high threshold for any proposal that adds `vcl_*{}`:  There needs to be a damn good reason, along the lines of Gettys rule no.1: "Do not add new functionality unless an implementor cannot complete a real application without it."

This proposal does not clear that barrier.

If knowing the hash-key in `vcl_recv{}` is the crucial thing, we can probably make it possible to explicitly call `vcl_hash{}` from `vcl_recv{}` to make that happen.

**Comment by nigoroll** [comment]
This has been discussed at length during bugwash. The discussion is to be continued during a later bugwash.

Meta-Info: I am writing up this summary with the best intents regarding objectivity and completeness. Please comment if you think I misrepresented parts of the discussion.

The suggested functionality can be summed up as "change req.* attributes relevant for lookup based on hash".

* @bsdphk has already explained his opinion and supported the idea of calling `vcl_hash{}` from `vcl_recv{}`. Concerns:
  * Problems due to inconsistencies about the applicable hash value (director: "i am using hash A", lookup: "i am using hash B")
      * "the confusion sounds scary"
  * VCL harder to read/understand
* Another option is a restart after `vcl_hash` (iow in `vcl_hit` or `vcl_pass`). Concerns:
  * restarts can be pretty evil when it comes to maintainability
  * requiring a restart also means doing two lookups, increasing any inherent race

Arguments pro this suggestion:
* would be 100% vcl backwards compatible with `sub vcl_lookup { return(ok); }` in `builtin.vcl`
* the FSM would be extended, but in the most simple way (basically just splitting `vcl_hash{}` in two)

Others ideas mentioned:
* `calc_hash;` in `vcl_hash{}`, which makes the hash final, and you can do stuff after that.
* remove `vcl_hash{}` altogether and moving `hash_data` to `vcl_revc{}`, Concerns:
  * same as calling `vcl_hash{};` from `vcl_revc{}`, see above

**Comment by nigoroll** [comment]
bugwash decision:
* add `sub vcl_lookup {}` to be called for `return(lookup)` from `vcl_recv {}` only. (that is, not for `pass`, `purge` and `pipe` or any other returns).
* the implicit call to `vcl_hash{}` remains

**Comment by nigoroll** [comment]
Following up to his veto on #3514, @bsdphk has committed a series of changes which bring `hash_data()` to `vcl_recv`, skipping `vcl_hash{}` if it was used. The documentation changes are in e98e8e6497b9bbcca3e709a5ea0e094f2ec4b930, other commits are d6ad52f5ff95daa3668fdad28b4c97e59b4c49d3, 4ebc3cfec133586cd8c4a715d8de18efb76402f1, 03fe0cee1abc3741a7652ba2cf9c1bf822d65ab1, e36573e255af2aa1ed40fb367fcb5257ef7e0288 and 001279ebd6ee83fafbc7fc1d1805bf2224361dd9

These changes were objected by @Dridi and @nigoroll via emails to -commit: https://varnish-cache.org/lists/pipermail/varnish-commit/2021-February/023982.html - see also other messages from that thread.

To summarize the objections:
* If the hash is used in `vcl_revc {}` for purposes like loadbalancing or blacklisting (saintmode), it must be avoided that the hash change after such use.
* The change could have unintended and silent consequences if, based on (a libraray of) existing VCL, 'hash_data()` is used in `vcl_recv{}`, leading to vital code in `vcl_hash{}` not being executed any more.

The following basic options on how to deal with this situation have been brought up:

a) revert the _hash_data in vcl_recv_ commits (see above), reiterate over possibly other ways on how to fix this issue
b) keep the _hash_data in vcl_recv_ commits and make them conditional on a feature flag
c) keep the _hash_data in vcl_recv_ commits and activate them only for vcl 4.2

@Dridi and @nigoroll so far voted for a), but this should be discussed during the next bugwash.

**Comment by bsdphk** [comment]
My position for the record:

On Procedure:
-------------

I have never consented to vcl_lookup{}:  See my comment above from march 23 2020, it still stands.

I did agree to look at a suggested implementation. 

That has now materialized, and I liked it precisly as little as I expected I would.

I dont see any obvious way I could have been more clear about this in my communication, but I will still strive to avoid repeats.

On Substance:
-------------

As I said on march 23 2020:  There is a "very high threshold" for adding a new `vcl_*{}`.

In many ways I consider that even adding `vcl_hash{}` was a mistake, but we had no realistic alternatives at the time, so that is a done deal, and I live with it. 

But I'm not repeating that mistake, which is why *none* of the many `vcl_*{}` I my self have talked about over the years have ever materialized.

In the present case, `vcl_lookup{}` is still no where near the threshold, and I have not even seen any attempt to get there. 

Ways to reach the threshold that would *mainly* be through VCL examples of what good `vcl_lookup{}` brings.

The one single use-case of extending TTL, when a backend doesnt like *a specific object*, is nowhere near enough.

( @nigoroll generalizes the use-case to "change req.* attributes relevant for lookup based on hash" above, but as Jim Gettys
admonishes us on http://varnish-cache.org/docs/trunk/dev-guide/index.html "The only thing worse than generalizing from one example is generalizing from no examples at all.")

Calling hash_data() in `vcl_recv{}`:
------------------------------------

The other way to make it possible for users to implement "change req.grace in response to backend not liking particular object" is to make it possible to finalize the hash already in `vcl_recv{}`.

I have added the ability to do that, with a net negative line-count, in a 100% backwards compatible way, which will not affect any users, unless and until they actively start to use it.

Objections have been raised about this "being to dangerous" and that it should therefore be backed out.

I find the calls for backout quite suspect, but I will consider them in good faith - once it is explained why *this* particular feature is too dangerous, considering all the other sharp tools we have no similar qualms supplying?

And even though I do not agree that this feature is "too dangerous", I am perfectly fine with neutering it, by adding a feature flag which must be enabled before `hash_data{}` is available in `vcl_recv{}`.

About the actual use case:
-------------------------- 
 
This particular use case has plagued us for more than a decade, and we have never found a good solution, because, there are none to be found within the fundamental architecture of Varnish.

It does however sound like a nice & smart feature though, which is probably why it keeps bubbling up. 

As a matter of record there is very little to support the notion that it is a "must have".
 
Absent a good solution, I am therefore perfectly willing to just say "Too bad, we cannot do that", and move on.
 
If we back out the the ability to call `hash_data{}` in `vcl_recv{}`, that *will* be the result.

A back-out does not in *any way* lower the threshold that must be met, to add new `vcl_*{}` methods.
 
/phk

**Comment by gquintard** [comment]
Chiming in from a user and teacher point of view, sorry if I missed something, I'm operating solely on this ticket and the `varnish-commits` mailing list.

I completely understand the reluctance to add routines as it add burden to the cognitive load, but I think that in this case, adding a new `vcl_lookup` would have made things easier for users, specially the new ones.

The vcl language has grown over the years and of course, there are some rough edges and ugly welds here and the biggest grievances I have are almost always about the lack of consistency, notably:
- `return (pass)` to force a pass, but `set req.hash_always_miss = true` to force a miss (there was a PR, dismissed for good reasons)
- `return(foo)` doesn't take you to `vcl_foo`, the model is fairly complex and I regularly lose trainees explaining this

In this specific case, I firmly believe that adding a new routine while decreasing modeling complexity is a nice step forward. With a `vcl_lookup` routine, the rules could be:
- `vcl_hash` after `vcl_recv`
- after `vcl_hash`, you get to the sub corresponding to your `return`, except for `lookup` that lands you in `vcl_hit` or `vcl_miss`, since it's not your choice

With `hash_data` in `vcl_recv`, we are closer to:
- `vcl_hash` after `vcl_recv`, even if you don't `return (hash)`, AND if you didn't call `hash_data` anywhere in `vcl_recv`
- if you `return` `pass` or `synth`, you go to the corresponding routine, except `hash` that lands you in `hit` or `miss`

And yes, I'm ignoring `restart` and other details, but my point is that while there would be one more routine, it would be more consistent and could be described with fewer rules, which is easier to apprehend.

The VCL is an incredibly powerful tool, but suffers from a higher barrier of entry that most configuration languages, and that's a price I happily pay given the power I get in return, but I think that, in this case, we can/should sacrifice a tiny bit of minimalism to get a less surprising language with fewer rules (POLA and all that).

Let's finish with a bang, even though I promise I'm not trolling: I would prefer to see the VCL evolve more freely and possibly "break" a fewer setups during major upgrades, rather than the current half-committed backward compatibility path that we seem to be on.

**Comment by bsdphk** [comment]
I'm not disputing there wouldn't be benefits by adding `vcl_lookup{}`, there would be.

They are just not anywhere big enough to justify it.

**Comment by nigoroll** [comment]
### On procedure:

I would like to add that the `hash_data()` change should better have been discussed as a PR.

### Calling `hash_data()` in `vcl_recv{}`:

Re @bsdphk 
> "being to dangerous"

I understand this is a paraphrase, but this is taking us in a direction where I did not want to go when I raised concerns. I will try to make them clearer, using some quotes from the -commit mails:


#### fixing the hash

> - Do we need a way to fix the hash within vcl_recv?
>
>  For example, if a backend decision has been made on the basis of the hash, we do not want it to change any more.

Consider this example

```
sub vcl_recv {
    hash_data(req.http.foo);
    set req.backend_hint = saintmode.backend(xyz);
    call some_sub;
}
```

If `some_sub` called `hash_data()`, the hash used for lookup would be different from the one used for `saintmode`.
The code would simply not do the right thing. Sure we can make this the users' problem, explain how it works and require users to make sure that things happen in the right order.  But...

> (...) Diri [has explained nicely how the "demarcation lines" between the fsm
states clearly are a superior concept](https://varnish-cache.org/lists/pipermail/varnish-commit/2021-February/023985.html), and with the hash_data change we would
have, to some degree, given up on it.

#### not calling vcl_hash

Consider this [example from -commit](https://varnish-cache.org/lists/pipermail/varnish-commit/2021-February/023984.html)

```
# included.vcl
vcl 4.1;

sub vcl_hash {
	hash_data("I rely on it");
}
```
```
# default.vcl
vcl 4.2;

include "included.vcl";

sub vcl_recv {
	hash_data(req.http.foo);
}
```

_If_ we go this route, my point is that we should use the vcl version to bail out from compilation of `included.vcl` because it has been written without knowledge of `hash_data()`.
My concern here is that, in real world code, it could become a substantial challenge to review an existing code base and identify the relevant cases once `hash_data()` is to be used in `vcl_recv{}` (as a solution to the actual problem).
Quote @bsdphk :
> in a 100% backwards compatible way, which will not affect any users, unless and until they actively start to use it

my concern is with the _unless_ bit

I agree that using a feature flag could be an alternative, I just don't understand why we would not use the mechanism which had been added for the purpose.

In general, I would like to emphasize that I am not so much concerned about my own piece of the planet here, but rather see this as a challenge for fellow companies in the project who run a challenging support business for many more clients than I do.

### Looking ahead

My current vote is for backout not because I thought the  `hash_data()` in `vcl_recv{}` idea was dead, but rather to have enough time for the necessary deliberation. Our, as I put it in [this email](https://varnish-cache.org/lists/pipermail/varnish-commit/2021-February/023988.html):

> Let's take the time to find the best possible solution and agree on it.

**Comment by Dridi** [comment]
I would like to apologize for jumping the gun too fast.

After giving a heads up that I was going to submit the `vcl_lookup` change, as I had convinced myself after so many months that it was the consensus, it seems that indeed that discussion was supposed to resume with that submission in the absence of clear-cut decision. There was no consensus, only https://github.com/varnishcache/varnish-cache/issues/3259#issuecomment-633589809 that misled me to believe that the matter was settled. I hope you will accept my apologies.

However, I also strongly disagree with the last-minute addition of `hash_data()` in `vcl_recv` with its lot of new exceptional cases, and as far as the FSM is concerned almost only exceptional/irregular cases. I already documented where this last-minute response to #3514 falls short in my opinion. And pushing documentation stating that it is a valid design pattern is not enough to convince me that it is indeed, and that it didn't deserve a discussion like #3514 almost had until I stopped being constructive.

**Comment by Dridi** [comment]
We ended up reverting the hash changes before the March release.

So we didn´t follow the plan that was decided but apparently not on May 25th, and didn´t change the hashing mechanic in a way that would fundamentally be broken relative to how we enforce read and write scope of pretty much all VCL symbols, some VMOD symbols and with VIP4 potentially all the VMOD symbols in the future: mapping scope to state machine steps (what `vcl_lookup` does).

**Comment by nigoroll** [comment]
continued in #3540
