### ISSUE TITLE
Impossible to produce JSON output with log-tools

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3297]
We have found agreement, that we want to ultimately change the internal VSL format so that structured (JSON) output can be produced, see [VIP23 - Refactor VSL...](https://github.com/varnishcache/varnish-cache/wiki/VIP-23:-Refactor-VSL-to-support-extracting-structured-data-from-"binary"-log-payloads). In other words, we want to output sensible structures and not just JSON formatting of the existing everything-is-a-string log entries.
With this background, #2869 has been rejected for a good reason, but I think we missed to salvage another very valid point from this PR: To my knowledge, it is not currently possible to output logs with JSON-escaped fields.

In my mind, we should have an option to at least be able to produce output with escaped strings to not break JSON-formatted output. This would not contraict the long term plan and avoid having to re-format output.
It seems [VS has implemented something like this](https://docs.varnish-software.com/varnish-cache-plus/features/json-logging/).

**Comment by nigoroll** [comment]
To clarify: The suggestion is to add the option for JSON quoting to `varnishcsa` only.

Bugwash is generally in favor. Comments made:
* `%{...}j` instead of `%{...}x` suggested by dridi, complementary to a `-j` flag
* phk noted `VSB_QUOTE_JSON` doesn't actually do the job
  * he suggests to restart with a cleaner `VSB_encode()` interface

VS uses a private API, so probably no interest to contribute their implementation

**Comment by xordspar0** [comment]
Currently we at Target use `varnishncsa` to manually build JSON logs with a `-F` format string. This would be an incremental improvement for us on the way to native JSON support in varnishlog.

**Comment by xordspar0** [comment]
@nigoroll Do you have an example of where the existing VSB_QUOTE_PLAIN or VSB_QUOTE_JSON is insufficient?

**Comment by nigoroll** [comment]
@xordspar0 no, I have not looked into this since I wrote the bugwash notes. Also the remark on `VSB_QUOTE_JSON` came from @bsdphk

**Comment by xordspar0** [comment]
> phk noted VSB_QUOTE_JSON doesn't actually do the job 

VSB_QUOTE_JSON does not ensure that the string is valid UTF-8, according to a comment in vsb.h:

https://github.com/varnishcache/varnish-cache/blob/cd86bd0ce46d07b40bf767f6c3e64aaeb554b840/include/vsb.h#L96

[The code](https://github.com/varnishcache/varnish-cache/blob/cd86bd0ce46d07b40bf767f6c3e64aaeb554b840/lib/libvarnish/vsb.c#L685-L686) and some manual tests verify that.

In fact, VSB_QUOTE_JSON is worse than VSB_QUOTE_PLAIN in this area, because PLAIN escapes all non-ascii characters with \xxx, while JSON copies non-ascii bytes unchanged.

> he suggests to restart with a cleaner VSB_encode() interface

I'm not sure what a "cleaner VSB_encode interface" would look like, but I'm guessing at least valid UTF-8 output is a requirement before this feature would be merged?

> %{...}j instead of %{...}x suggested by dridi, complementary to a -j flag

`%{...}j` would work for `%{...}x`-style format specifiers, but how would it work for `%{...}i` and `%{...}o`? Is it ok to just add a `-j` option that switches all format specifiers to output valid JSON strings?
