### ISSUE TITLE
header names can not be numbers

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3379]
fallout from something unrelated:

```
**** v1   CLI RX|Message from VCC-compiler:
**** v1   CLI RX|Symbol 'resp.http' has wrong type (none): 
**** v1   CLI RX|At: ('<vcl.inline>' Line 16 Pos 21) -- (Pos 29)
**** v1   CLI RX|                set resp.http.123 = "abc";
**** v1   CLI RX|--------------------#########-------------
```

**Comment by bsdphk** [comment]
I'm inclined to invoke the inverse-postel principle and just say "too bad"

**Comment by Dridi** [comment]
This is the fallout of #2573 that resulted in header names following the rules of VCL symbol names, without a syntax for otherwise valid HTTP header names that aren't valid for symbols.

My proposal has always been `resp.http[123]` because `[` and `]` are HTTP separators and not valid for header names, and this syntax might be familiar to other programming languages that support associative arrays.

**Comment by nigoroll** [comment]
also kind-of duplicate to #3103 as pointed out by @Dridi

**Comment by nigoroll** [comment]
has been discussed again, vmods can do the job, I will docfix and then close
