### ISSUE TITLE
libvarnishapi version mismatch

### ISSUE THREAD

**Issue by rezan** [varnishcache/varnish-cache#3397]
For `6.0`, it looks like there is a mismatch for the `libvarnishapi` version, `1.6` here:

https://github.com/varnishcache/varnish-cache/blob/18bf1d491bf857f05b703c29f690d1be33a9bddc/lib/libvarnishapi/Makefile.am#L12

And `2.0` here:

https://github.com/varnishcache/varnish-cache/blob/18bf1d491bf857f05b703c29f690d1be33a9bddc/lib/libvarnishapi/libvarnishapi.map#L29

This issue https://github.com/varnishcache/varnish-cache/pull/2718 addressed a fix in `master`, but `6.0` was not touched.

I think we should at least converge on a single version, just not sure what the pros/cons are for changing this.

Reported by @ema

**Comment by rezan** [comment]
Discussion with @dridi on IRC:

* Changing any of these versions is likely very bad
* Possibility to **add** 1.6 as identical version to 2.0 in the map file?

**Comment by Dridi** [comment]
Not quite what I said, but in essence:

- we can't break the `libvarnishapi.so.1` soname in a stable series, too bad we missed the mark then
- the map file is for symbol versioning, we may add new symbols but not change them on a stable branch
  - if a system supports the map file it also clears the visibility of any unlisted symbol (a nice addition)

As a matter of fact, `1:6:0` is not even a valid version triplet for libtool, but it doesn't matter much. We fixed it when we went `2:0:0` but then utterly failed to do minor bumps when we added symbols without breaking. I'm willing to take the blame for that, next libvarnishapi major soname bump I can try to document how not to screw up agaim.

We could also have 1.x symbols in `libvarnishapi.so.2`, provided that they effectively didn't change, which we didn't bother with at the time in favor of a clean slate in the map file. It doesn't make a difference since it was a major soname bump anyway.

My verdict is WONTFIX. I can help review future additions to libvarnishapi to make sure we don't break binary stability.

**Comment by rezan** [comment]
@ema does the following lines at the end of `libvarnishapi.map` resolve your problem:

``` 
LIBVARNISHAPI_1.6 {
} LIBVARNISHAPI_2.0;
```

This basically adds 1.6 as a copy of the existing 2.0 symbols. When I look at the resulting shared object, it has both 1.6 and 2.0 symbols. So this does seem to be an additive change.

Also, as Dridi said, I think we have the versioning wrong, the shared object is versioned `1.0.6`, not `1.6.0`. Does the above `LIBVARNISHAPI_1.6` match that?

**Comment by Dridi** [comment]
EWONTFIX
