### ISSUE TITLE
VCL macros

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#3584]
@nigoroll had me looking at ACL's including other ACL's:

    acl acl2 {
        rule;
        rule;
        acl1;
        rule;
    }

And while researching this I came up with a more general idea:

    macro foobar {
            sequence of tokens, including matched { ... }
    }

Then anywhere the token `foobar` is encountered, all the tokens inside the { ... } are substituted.

Would this have any other credible use-cases apart from ACLs ?

**Comment by Dridi** [comment]
Backend or probe arguments (especially probe `.request`) come to mind.

**Comment by Dridi** [comment]
What about `macro foo(bar, baz) { ... }`?

**Comment by bsdphk** [comment]
Macros with arguments are always becomes a syntactic mess, because you need an "overlay" syntax to make the places the arguments should be expanded stand out.

See also: C++ templates.

I'm not against macro arguments as such, but I would like to postpone them until later.

**Comment by nigoroll** [comment]
> Would this have any other credible use-cases apart from ACLs ?

Regarding the broader picture:

This sounds like it could be a step into the direction of templating VCL in VCL, rather than some other language (I am personally using a whole bunch, including [pure perl](https://www.perl.org/), [ERB](https://docs.ruby-lang.org/en/2.3.0/ERB.html) and [go templates](https://golang.org/pkg/text/template/)).

So on the pro side, macro expansion could solve some of the problems otherwise solved with external templating, but on the con side, I can see that as long as we do not offer a full-featured language (which was then used for templating), external templating will remain the better investment, as one was likely to hit a wall sooner or later with limited templating capabilities.

Taking a step back, macros could replace the de-facto macro-expansion we currently have with include.

**Comment by bsdphk** [comment]
Continued in PR #3610
