### ISSUE TITLE
Varnish 4.1 + Drupal 7 + Leaflet 1.6 = js with "*"

### ISSUE THREAD

**Issue by denics** [varnishcache/varnish-cache#3612]
*Step to reproduce:*
- Install Varnish 4.1, Drupal 7.80, Leafletjs 1.6
- Enable js preprocess in Drupal
- All Leaflet maps are broken

*Expected behavior*
Preprocessing js in Drupal is very important to optimize site speed and load.

*Current behavior*
Some, very randomly, Lat or Long are replaced by ,***** kind of format which break LeafletJS. However the right values are in the DB. Without varnish, no problem.

*Environment*
- Browser (with version): browser independent
- OS/Platform (with version): OS independent

You can see the problem happening here: https://en.unesco.org/countries

Without varnish:
![image](https://user-images.githubusercontent.com/2407163/117833914-059d9d80-b277-11eb-8a39-9118b2dd7336.png)

with varnish:
![image](https://user-images.githubusercontent.com/2407163/117834369-60cf9000-b277-11eb-9996-b816fa0e1028.png)

**Comment by bsdphk** [comment]
can you capture the output of varnishlog and share it with us ?  (If need by email...)

**Comment by bsdphk** [comment]
I tried your link, and I see no similar messages in my developer console.

**Comment by nigoroll** [comment]
Sorry, I really feel bad about a harsh reaction as this seems to be Varnish used for a very good cause (and I love radio), but it is our policy to not use github issues for support, only for bugs.
I think we should stick to that policy no matter who reports an issue.
So:
* @denics please refer to https://varnish-cache.org/support/index.html for support
* As Dridi said, 4.1 is long EOL, see https://varnish-cache.org/releases/index.html
* I do not think this is an issue in varnish-cache, if you disagree and can show the issue using varnishlog or otherwise, please reopen this ticket with relevant information

As a general statement, "it works if I disable varnish" is usually related to an application using some request headers without the appropriate `Vary`.
