### ISSUE TITLE
vadmin_run (modules/vadmin.c:241): Communication error with varnishd.

### ISSUE THREAD

**Issue by Neurobion** [varnishcache/varnish-cache#3651]
Hi, I would like to ask you what exactly mean these messages in syslog:

```
Jul 23 14:20:03 XX varnish-agent[2156]: vadmin_run (modules/vadmin.c:241): Communication error with varnishd.
Jul 23 14:20:03 XX varnish-agent[2156]: vping_run (modules/vping.c:63): Ping failed. 400
Jul 23 14:20:03 XX varnish-agent[2156]: n_arg_sock (modules/vadmin.c:134): -T argument computed to: 127.0.0.1 6082
```

**Comment by Dridi** [comment]
These messages come from https://github.com/varnish/vagent2 which is no longer maintained and compatible with Varnish 4.1 that is EOL. I will close this ticket on account of being a general question, the issue template states that general questions can be asked via the mailing list and we want to reserve github issues for actionable bugs.

To answer your question, a Varnish server is operated with a command line interface (or CLI, see https://varnish-cache.org/docs/trunk/reference/#the-cli-interface) and if you are using a recent version of Varnish with the old agent it may fail to ping because of changes to the CLI since Varnish 4.1.
