### ISSUE TITLE
`varnishadm vcl.list  -j` produces not parsable JSON with status code on the first line

### ISSUE THREAD

**Issue by rhajek** [varnishcache/varnish-cache#3687]
## Expected behavior

`varnishadm vcl.list  -j` should produce a valid json, but the output contains status code `200` on the first line, which is not parsable.

The status code is also added to the first line in the text output mode without -j parameter. 

## Steps to Reproduce (for bugs)
Run server:
```
docker run --rm --name varnish varnish:6.6
```

Run varnishadm
```
docker exec -it varnish varnishadm vcl.list  -j 
```

output:

```json
200
[ 2, ["vcl.list", "-j"], 1631021700.200,
  {
    "status": "active",
    "state": "auto",
    "temperature": "warm",
    "busy": 0,
    "name": "boot"
}
]
```
It affects only latest varnish version, output from `varnishadm vcl.list  -j` in older `varnish-6.5.1` returns valid json, there is no status on the first line.

## Possible Solution
Remove 200 status from json output

## Your Environment
docker, macosx

**Comment by Dridi** [comment]
I would agree this is a regression, and only `varnishadm -p` should give us the status. This change also happened for non-JSON output and I think it should be reverted.

There are tools relying on the output, and that reminded me of this thread:

https://varnish-cache.org/lists/pipermail/varnish-misc/2021-June/027035.html

The problem is different but the `varnishreload` script could very well be affected by the status showing up too.

**Comment by Dridi** [comment]
https://github.com/varnishcache/varnish-cache/pull/3691

**Comment by nigoroll** [comment]
FTR:
@Dridi dug out the commit which changed behaviour: since eb3c0e11e0e829ff6f23fda43f817d9f04e8cfaa the status was added to vcl.list.
So this really is a regression, and status output should be limited to `-p` (with the length as per CLI protocol)
