### ISSUE TITLE
H2 to backend possible or planned?

### ISSUE THREAD

**Issue by dgaastra** [varnishcache/varnish-cache#3712]
Dear Varnish developers,

Thanks for developing such a great product. We are fairly new to Varnish System and are wondering if H2 to the backend would be possible or is already in the works? Or does it not make any sense? One could argue, that initially uncached requests could benefit, if such requests were piped H2 all the way to the backend. Currently, the (say) Apache backend gets HTTP/1.1  requests from Varnish with the front-end of Varnish being HTTP/2.

Dennis

**Comment by bsdphk** [comment]
I dont know of any current plans, because there are some worrying downsides to using H2 between Varnish and the backends.

H2 (as predicted before it was ever created) suffers from "Head-Of-Line-Blocking" when packets get lost or dropped, this causes all requests on that H2 connection to get delayed while TCP sorts out the retransmission etc.

If this happened on a hypothetical H2 connection between Varnish and a backend, that would delay a lot of transactions, because of the "multiplexing" Varnish does, whereas with HTTP/1.1 only a single transaction is affected.

There are also concerns with respect to how well the HPACK compression works, and if the backend server offers big enough H2 "windows" to cope efficiently with the kind of "concentrated" traffic a Varnish would cause.

So all in all it is not obvious that it would be time well spent.
