### ISSUE TITLE
Whether the LTS version can adapt to the PCRE2?

### ISSUE THREAD

**Issue by lzy-daze** [varnishcache/varnish-cache#3808]
Hello!
The older PCRE library is released in the 1990s and is now at end of life. The newer PCRE2 library is being actively maintained.
However, the LTS version still supports only PCRE. Although LTS is still being released iteratively。
I know the latest release version has supported PCRE2, but whether the LTS version can adapt to the PCRE2?
Do you have any plans？

**Comment by Dridi** [comment]
We are very much aware of the current state of PCRE and PCRE2, and this is the reason why we performed the migration in the first place. There are no plans to do the same for the 6.0 LTS series since the migration resulted in small and subtle breaking changes. Even though most regex usage in Varnish should not be affected by this migration, it is unfit for a stable branch.

It could be reconsidered if a major security incident happened with PCRE.

Also, the issue template makes it very clear that we only want actual bug reports and not general questions.
