### ISSUE TITLE
VCL Can be compiled in advance?

### ISSUE THREAD

**Issue by MiuNice** [varnishcache/varnish-cache#3885]
Is it feasible to consider compiling vcl files in advance without gcc installed on the server?

**Comment by Dridi** [comment]
As stated in the issue template we only want github issues for actual bug reports. For general discussions, please use the misc mailing list.

The short answer is yes, but it's complicated.

**Comment by gquintard** [comment]
@MiuNice , in order to not leave you hanging, you can check this preliminary work: https://github.com/varnish/toolbox/pull/7

if you have questions, remarks or anything else, I would recommend the [discord server](https://discord.com/invite/EuwdvbZR6d) or the misc mailing list, but any of the channels listed [on the help page](https://varnish-cache.org/support/) will get you started and are the preferred ways for regular non-bug support.
