### ISSUE TITLE
Assert error in wrk_thread_real

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#985]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/985

**Comment by thimoonxy** [comment]
We are facing simillar error in 3.0.2-1ubuntu0.1, child process is restarted by master very frequently which triggers about 4.51% 503 errors, but we already use -s Transient=malloc,256m mentioned in Trac ticket. What else I can do to fix this issue?
`Panic message: Assert error in wrk_thread_real(), cache_pool.c line 188:#012  Condition((w->beresp->ws) == 0) not true.#012thread = (cache-worker)#012ident = Linux,3.13.0-32-generic,x86_64,-smalloc,-smalloc,-hcritbit,epoll#012Backtrace:#012  0x42f965: /usr/sbin/varnishd() [0x42f965]#012  0x4318a7: /usr/sbin/varnishd() [0x4318a7]#012  0x7f610d4cfe9a: /lib/x86_64-linux-gnu/libpthread.so.0(+0x7e9a) [0x7f610d4cfe9a]#012  0x7f610d1fd38d: /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f610d1fd38d]#012`

**Comment by hermunn** [comment]
The problem may have been fixed in the current Varnish 3 version, 3.0.7. All prior versions of Varnish Cache 3 are not maintained.

If you consider upgrading to Varnish Cache 4.1.2 (please do), you can try @fgsch's script found at https://github.com/fgsch/varnish3to4. You can also read about the changes from 3 to 4 on https://www.varnish-cache.org/docs/4.0/whats-new/upgrading.html. With some luck, upgrading to Varnish Cache 4 will not be too much work.

**Comment by lkarsten** [comment]
Backport review: 3.0 is end of life.

**Comment by Jailman** [comment]
So an update would fix this?

**Comment by Jailman** [comment]
So an update would fix this?

**Comment by nigoroll** [comment]
@Jailman yes that's what @hermunn said
